services:

  ohm-dev:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ohm-dev:latest
      target: build
    volumes:
      - .:/local
    command: ["shell"]
    # command: ["-o", "ohm-grammar.wasm", "packages/ohm-js/src/ohm-grammar.ohm"]
