services:

  ohm:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ohm:latest
        - ${DOCKER_REPO:-ohmjs}/ohm:${VERSION:-development}
      target: dist
    volumes:
      - .:/local
    command: ["help"]
