packages:
  - 'packages/*'
  - 'examples/attributes'
  - 'examples/ecmascript'
  - 'examples/es-module'
  - 'examples/markdown'
  - 'examples/indentation-sensitive'
  - 'examples/operators'
  - 'examples/simple-lisp'
  - 'examples/typescript'

ignoredBuiltDependencies:
  - esbuild

pnpm:
  allowBuild:
    - esbuild

linkWorkspacePackages: true

minimumReleaseAge: 1440
