// Code generated by ohmgo generate accepts - DO NOT EDIT.
package ohm_rules

import (
	"github.com/ohmjs/goohm"
)

// accepts for grammar Ohm

// TODO for grammar Ohm, implement Make func for starting rule Grammars

// Accept implementation for Grammars
//
// Grammars
// = Grammar*
func (node *Grammars[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Grammars")
	if v, ok := visitor.(VisitorGrammars[P, R]); ok {
		return v.VisitGrammars(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Grammars[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptGrammar(visitor, payload)
	return
}

func (node *Grammars[P, R]) AcceptGrammar(visitor any, payload P) (result R) {
	for _, n := range node.Grammar.Children() {
		kids := n.Children()
		result = (&Grammar[P, R]{
			Ident:        kids[0].(goohm.RuleNode),
			SuperGrammar: kids[1].(goohm.OptNode),
			Term1:        kids[2].(goohm.TerminalNode),
			Rule:         kids[3].(goohm.ListNode),
			Term2:        kids[4].(goohm.TerminalNode),
		}).Accept(n, visitor, payload)
	}
	return
}

// Accept implementation for Grammar
//
// Grammar
// = ident SuperGrammar? "{" Rule* "}"
func (node *Grammar[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Grammar")
	if v, ok := visitor.(VisitorGrammar[P, R]); ok {
		return v.VisitGrammar(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Grammar[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexIdent(visitor, payload)
	result = node.AcceptSuperGrammar(visitor, payload)
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptRule(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *Grammar[P, R]) AcceptLexIdent(visitor any, payload P) (result R) {
	// Rule
	kids := node.Ident.Children()
	result = (&LexIdent[P, R]{
		Name: kids[0].(goohm.RuleNode),
	}).Accept(node.Ident, visitor, payload)
	return
}

func (node *Grammar[P, R]) AcceptSuperGrammar(visitor any, payload P) (result R) {
	// Opt
	if len(node.SuperGrammar.Children()) > 0 {
		n := node.SuperGrammar.Children()[0]
		kids := n.Children()
		result = (&SuperGrammar[P, R]{
			Term:  kids[0].(goohm.TerminalNode),
			Ident: kids[1].(goohm.RuleNode),
		}).Accept(n, visitor, payload)
	}
	return
}

func (node *Grammar[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *Grammar[P, R]) AcceptRule(visitor any, payload P) (result R) {
	for _, n := range node.Rule.Children() {
		result = (&Rule[P, R]{
			Node: n,
				}).Accept(n, visitor, payload)
	}
	return
}

func (node *Grammar[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for SuperGrammar
//
// SuperGrammar
// = "<:" ident
func (node *SuperGrammar[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "SuperGrammar")
	if v, ok := visitor.(VisitorSuperGrammar[P, R]); ok {
		return v.VisitSuperGrammar(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *SuperGrammar[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptLexIdent(visitor, payload)
	return
}

func (node *SuperGrammar[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *SuperGrammar[P, R]) AcceptLexIdent(visitor any, payload P) (result R) {
	// Rule
	kids := node.Ident.Children()
	result = (&LexIdent[P, R]{
		Name: kids[0].(goohm.RuleNode),
	}).Accept(node.Ident, visitor, payload)
	return
}

// Accept implementation for Rule
//
// Rule
// = ident Formals? ruleDescr? "="  RuleBody  -- define
// | ident Formals?            ":=" OverrideRuleBody  -- override
// | ident Formals?            "+=" RuleBody  -- extend
func (node *Rule[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Rule")
	if v, ok := visitor.(VisitorRule[P, R]); ok {
		return v.VisitRule(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Rule[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "Rule":
		return (&Rule[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "Rule_define":
		kids := node.Node.Children()
		return (&RuleDefine[P, R]{
			Ident:     kids[0].(goohm.RuleNode),
			Formals:   kids[1].(goohm.OptNode),
			RuleDescr: kids[2].(goohm.OptNode),
			Term:      kids[3].(goohm.TerminalNode),
			RuleBody:  kids[4].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "Rule_override":
		kids := node.Node.Children()
		return (&RuleOverride[P, R]{
			Ident:            kids[0].(goohm.RuleNode),
			Formals:          kids[1].(goohm.OptNode),
			Term:             kids[2].(goohm.TerminalNode),
			OverrideRuleBody: kids[3].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "Rule_extend":
		kids := node.Node.Children()
		return (&RuleExtend[P, R]{
			Ident:    kids[0].(goohm.RuleNode),
			Formals:  kids[1].(goohm.OptNode),
			Term:     kids[2].(goohm.TerminalNode),
			RuleBody: kids[3].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for Rule_define
//
// ident Formals? ruleDescr? "="  RuleBody
func (node *RuleDefine[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Rule_define")
	if v, ok := visitor.(VisitorRuleDefine[P, R]); ok {
		return v.VisitRuleDefine(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *RuleDefine[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexIdent(visitor, payload)
	result = node.AcceptFormals(visitor, payload)
	result = node.AcceptLexRuleDescr(visitor, payload)
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptRuleBody(visitor, payload)
	return
}

func (node *RuleDefine[P, R]) AcceptLexIdent(visitor any, payload P) (result R) {
	// Rule
	kids := node.Ident.Children()
	result = (&LexIdent[P, R]{
		Name: kids[0].(goohm.RuleNode),
	}).Accept(node.Ident, visitor, payload)
	return
}

func (node *RuleDefine[P, R]) AcceptFormals(visitor any, payload P) (result R) {
	// Opt
	if len(node.Formals.Children()) > 0 {
		n := node.Formals.Children()[0]
		kids := n.Children()
		result = (&Formals[P, R]{
			Term1:  kids[0].(goohm.TerminalNode),
			ListOf: kids[1].(goohm.BHorNode),
			Term2:  kids[2].(goohm.TerminalNode),
		}).Accept(n, visitor, payload)
	}
	return
}

func (node *RuleDefine[P, R]) AcceptLexRuleDescr(visitor any, payload P) (result R) {
	// Opt
	if len(node.RuleDescr.Children()) > 0 {
		n := node.RuleDescr.Children()[0]
		kids := n.Children()
		result = (&LexRuleDescr[P, R]{
			Term1:         kids[0].(goohm.TerminalNode),
			RuleDescrText: kids[1].(goohm.RuleNode),
			Term2:         kids[2].(goohm.TerminalNode),
		}).Accept(n, visitor, payload)
	}
	return
}

func (node *RuleDefine[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *RuleDefine[P, R]) AcceptRuleBody(visitor any, payload P) (result R) {
	// Rule
	kids := node.RuleBody.Children()
	result = (&RuleBody[P, R]{
		Term:           kids[0].(goohm.OptNode),
		NonemptyListOf: kids[1].(goohm.BHorNode),
	}).Accept(node.RuleBody, visitor, payload)
	return
}

// Accept implementation for Rule_override
//
// ident Formals?            ":=" OverrideRuleBody
func (node *RuleOverride[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Rule_override")
	if v, ok := visitor.(VisitorRuleOverride[P, R]); ok {
		return v.VisitRuleOverride(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *RuleOverride[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexIdent(visitor, payload)
	result = node.AcceptFormals(visitor, payload)
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptOverrideRuleBody(visitor, payload)
	return
}

func (node *RuleOverride[P, R]) AcceptLexIdent(visitor any, payload P) (result R) {
	// Rule
	kids := node.Ident.Children()
	result = (&LexIdent[P, R]{
		Name: kids[0].(goohm.RuleNode),
	}).Accept(node.Ident, visitor, payload)
	return
}

func (node *RuleOverride[P, R]) AcceptFormals(visitor any, payload P) (result R) {
	// Opt
	if len(node.Formals.Children()) > 0 {
		n := node.Formals.Children()[0]
		kids := n.Children()
		result = (&Formals[P, R]{
			Term1:  kids[0].(goohm.TerminalNode),
			ListOf: kids[1].(goohm.BHorNode),
			Term2:  kids[2].(goohm.TerminalNode),
		}).Accept(n, visitor, payload)
	}
	return
}

func (node *RuleOverride[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *RuleOverride[P, R]) AcceptOverrideRuleBody(visitor any, payload P) (result R) {
	// Rule
	kids := node.OverrideRuleBody.Children()
	result = (&OverrideRuleBody[P, R]{
		Term:           kids[0].(goohm.OptNode),
		NonemptyListOf: kids[1].(goohm.BHorNode),
	}).Accept(node.OverrideRuleBody, visitor, payload)
	return
}

// Accept implementation for Rule_extend
//
// ident Formals?            "+=" RuleBody
func (node *RuleExtend[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Rule_extend")
	if v, ok := visitor.(VisitorRuleExtend[P, R]); ok {
		return v.VisitRuleExtend(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *RuleExtend[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexIdent(visitor, payload)
	result = node.AcceptFormals(visitor, payload)
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptRuleBody(visitor, payload)
	return
}

func (node *RuleExtend[P, R]) AcceptLexIdent(visitor any, payload P) (result R) {
	// Rule
	kids := node.Ident.Children()
	result = (&LexIdent[P, R]{
		Name: kids[0].(goohm.RuleNode),
	}).Accept(node.Ident, visitor, payload)
	return
}

func (node *RuleExtend[P, R]) AcceptFormals(visitor any, payload P) (result R) {
	// Opt
	if len(node.Formals.Children()) > 0 {
		n := node.Formals.Children()[0]
		kids := n.Children()
		result = (&Formals[P, R]{
			Term1:  kids[0].(goohm.TerminalNode),
			ListOf: kids[1].(goohm.BHorNode),
			Term2:  kids[2].(goohm.TerminalNode),
		}).Accept(n, visitor, payload)
	}
	return
}

func (node *RuleExtend[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *RuleExtend[P, R]) AcceptRuleBody(visitor any, payload P) (result R) {
	// Rule
	kids := node.RuleBody.Children()
	result = (&RuleBody[P, R]{
		Term:           kids[0].(goohm.OptNode),
		NonemptyListOf: kids[1].(goohm.BHorNode),
	}).Accept(node.RuleBody, visitor, payload)
	return
}

// Accept implementation for RuleBody
//
// RuleBody
// = "|"? NonemptyListOf<TopLevelTerm, "|">
func (node *RuleBody[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "RuleBody")
	if v, ok := visitor.(VisitorRuleBody[P, R]); ok {
		return v.VisitRuleBody(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *RuleBody[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptNonemptyListOf(visitor, payload)
	return
}

func (node *RuleBody[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Opt
	if len(node.Term.Children()) > 0 {
		n := node.Term.Children()[0]
		if v, ok := visitor.(goohm.TerminalVisitor); ok {
			v.Terminal(n.(goohm.TerminalNode))
		}
	}
	return
}

func (node *RuleBody[P, R]) AcceptNonemptyListOf(visitor any, payload P) (result R) {
	// BuiltinHOR
	// TopLevelTerm
	fn_elem := func(n goohm.Node) (result R) {
		kids := n.Children()
		result = (&TopLevelTerm[P, R]{
			Node: kids[0],
		}).Accept(n, visitor, payload)
		return
	}
	fn_sep := func(n goohm.Node) (result R) {
		if v, ok := visitor.(goohm.TerminalVisitor); ok {
			v.Terminal(n.(goohm.TerminalNode))
		}
		return
	}
	goohm.AcceptBuiltinHOR(node.NonemptyListOf, fn_elem, fn_sep)
	return
}

// Accept implementation for TopLevelTerm
//
// TopLevelTerm
// = Seq caseName  -- inline
// | Seq
func (node *TopLevelTerm[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "TopLevelTerm")
	if v, ok := visitor.(VisitorTopLevelTerm[P, R]); ok {
		return v.VisitTopLevelTerm(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *TopLevelTerm[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "TopLevelTerm":
		return (&TopLevelTerm[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "TopLevelTerm_inline":
		kids := node.Node.Children()
		return (&TopLevelTermInline[P, R]{
			Seq:      kids[0].(goohm.RuleNode),
			CaseName: kids[1].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "Seq":
		kids := node.Node.Children()
		return (&Seq[P, R]{
			Iter: kids[0].(goohm.ListNode),
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for TopLevelTerm_inline
//
// Seq caseName
func (node *TopLevelTermInline[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "TopLevelTerm_inline")
	if v, ok := visitor.(VisitorTopLevelTermInline[P, R]); ok {
		return v.VisitTopLevelTermInline(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *TopLevelTermInline[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptSeq(visitor, payload)
	result = node.AcceptLexCaseName(visitor, payload)
	return
}

func (node *TopLevelTermInline[P, R]) AcceptSeq(visitor any, payload P) (result R) {
	// Rule
	kids := node.Seq.Children()
	result = (&Seq[P, R]{
		Iter: kids[0].(goohm.ListNode),
	}).Accept(node.Seq, visitor, payload)
	return
}

func (node *TopLevelTermInline[P, R]) AcceptLexCaseName(visitor any, payload P) (result R) {
	// Rule
	kids := node.CaseName.Children()
	result = (&LexCaseName[P, R]{
		Term: kids[0].(goohm.TerminalNode),
		Alt1: kids[1].(goohm.ListNode),
		Name: kids[2].(goohm.RuleNode),
		Alt2: kids[3].(goohm.ListNode),
		Alt3: kids[4],
	}).Accept(node.CaseName, visitor, payload)
	return
}

// Accept implementation for OverrideRuleBody
//
// OverrideRuleBody
// = "|"? NonemptyListOf<OverrideTopLevelTerm, "|">
func (node *OverrideRuleBody[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "OverrideRuleBody")
	if v, ok := visitor.(VisitorOverrideRuleBody[P, R]); ok {
		return v.VisitOverrideRuleBody(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *OverrideRuleBody[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptNonemptyListOf(visitor, payload)
	return
}

func (node *OverrideRuleBody[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Opt
	if len(node.Term.Children()) > 0 {
		n := node.Term.Children()[0]
		if v, ok := visitor.(goohm.TerminalVisitor); ok {
			v.Terminal(n.(goohm.TerminalNode))
		}
	}
	return
}

func (node *OverrideRuleBody[P, R]) AcceptNonemptyListOf(visitor any, payload P) (result R) {
	// BuiltinHOR
	// OverrideTopLevelTerm
	fn_elem := func(n goohm.Node) (result R) {
		kids := n.Children()
		result = (&OverrideTopLevelTerm[P, R]{
			Node: kids[0],
		}).Accept(n, visitor, payload)
		return
	}
	fn_sep := func(n goohm.Node) (result R) {
		if v, ok := visitor.(goohm.TerminalVisitor); ok {
			v.Terminal(n.(goohm.TerminalNode))
		}
		return
	}
	goohm.AcceptBuiltinHOR(node.NonemptyListOf, fn_elem, fn_sep)
	return
}

// Accept implementation for OverrideTopLevelTerm
//
// OverrideTopLevelTerm
// = "..."  -- superSplice
// | TopLevelTerm
func (node *OverrideTopLevelTerm[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "OverrideTopLevelTerm")
	if v, ok := visitor.(VisitorOverrideTopLevelTerm[P, R]); ok {
		return v.VisitOverrideTopLevelTerm(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *OverrideTopLevelTerm[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "OverrideTopLevelTerm":
		return (&OverrideTopLevelTerm[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "OverrideTopLevelTerm_superSplice":
		kids := node.Node.Children()
		return (&OverrideTopLevelTermSuperSplice[P, R]{
			Term: kids[0].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "TopLevelTerm":
		kids := node.Node.Children()
		return (&TopLevelTerm[P, R]{
			Node: kids[0],
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for OverrideTopLevelTerm_superSplice
//
// "..."
func (node *OverrideTopLevelTermSuperSplice[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "OverrideTopLevelTerm_superSplice")
	if v, ok := visitor.(VisitorOverrideTopLevelTermSuperSplice[P, R]); ok {
		return v.VisitOverrideTopLevelTermSuperSplice(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *OverrideTopLevelTermSuperSplice[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *OverrideTopLevelTermSuperSplice[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for Formals
//
// Formals
// = "<" ListOf<ident, ","> ">"
func (node *Formals[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Formals")
	if v, ok := visitor.(VisitorFormals[P, R]); ok {
		return v.VisitFormals(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Formals[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptListOf(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *Formals[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *Formals[P, R]) AcceptListOf(visitor any, payload P) (result R) {
	// BuiltinHOR
	// ident
	fn_elem := func(n goohm.Node) (result R) {
		kids := n.Children()
		result = (&LexIdent[P, R]{
			Name: kids[0].(goohm.RuleNode),
		}).Accept(n, visitor, payload)
		return
	}
	fn_sep := func(n goohm.Node) (result R) {
		if v, ok := visitor.(goohm.TerminalVisitor); ok {
			v.Terminal(n.(goohm.TerminalNode))
		}
		return
	}
	goohm.AcceptBuiltinHOR(node.ListOf, fn_elem, fn_sep)
	return
}

func (node *Formals[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for Params
//
// Params
// = "<" ListOf<Seq, ","> ">"
func (node *Params[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Params")
	if v, ok := visitor.(VisitorParams[P, R]); ok {
		return v.VisitParams(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Params[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptListOf(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *Params[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *Params[P, R]) AcceptListOf(visitor any, payload P) (result R) {
	// BuiltinHOR
	// Seq
	fn_elem := func(n goohm.Node) (result R) {
		kids := n.Children()
		result = (&Seq[P, R]{
			Iter: kids[0].(goohm.ListNode),
		}).Accept(n, visitor, payload)
		return
	}
	fn_sep := func(n goohm.Node) (result R) {
		if v, ok := visitor.(goohm.TerminalVisitor); ok {
			v.Terminal(n.(goohm.TerminalNode))
		}
		return
	}
	goohm.AcceptBuiltinHOR(node.ListOf, fn_elem, fn_sep)
	return
}

func (node *Params[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for Alt
//
// Alt
// = NonemptyListOf<Seq, "|">
func (node *Alt[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Alt")
	if v, ok := visitor.(VisitorAlt[P, R]); ok {
		return v.VisitAlt(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Alt[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptNonemptyListOf(visitor, payload)
	return
}

func (node *Alt[P, R]) AcceptNonemptyListOf(visitor any, payload P) (result R) {
	// BuiltinHOR
	// Seq
	fn_elem := func(n goohm.Node) (result R) {
		kids := n.Children()
		result = (&Seq[P, R]{
			Iter: kids[0].(goohm.ListNode),
		}).Accept(n, visitor, payload)
		return
	}
	fn_sep := func(n goohm.Node) (result R) {
		if v, ok := visitor.(goohm.TerminalVisitor); ok {
			v.Terminal(n.(goohm.TerminalNode))
		}
		return
	}
	goohm.AcceptBuiltinHOR(node.NonemptyListOf, fn_elem, fn_sep)
	return
}

// Accept implementation for Seq
//
// Seq
// = Iter*
func (node *Seq[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Seq")
	if v, ok := visitor.(VisitorSeq[P, R]); ok {
		return v.VisitSeq(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Seq[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptIter(visitor, payload)
	return
}

func (node *Seq[P, R]) AcceptIter(visitor any, payload P) (result R) {
	for _, n := range node.Iter.Children() {
		result = (&Iter[P, R]{
			Node: n,
				}).Accept(n, visitor, payload)
	}
	return
}

// Accept implementation for Iter
//
// Iter
// = Pred "*"  -- star
// | Pred "+"  -- plus
// | Pred "?"  -- opt
// | Pred
func (node *Iter[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Iter")
	if v, ok := visitor.(VisitorIter[P, R]); ok {
		return v.VisitIter(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Iter[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "Iter":
		return (&Iter[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "Iter_star":
		kids := node.Node.Children()
		return (&IterStar[P, R]{
			Pred: kids[0].(goohm.RuleNode),
			Term: kids[1].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "Iter_plus":
		kids := node.Node.Children()
		return (&IterPlus[P, R]{
			Pred: kids[0].(goohm.RuleNode),
			Term: kids[1].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "Iter_opt":
		kids := node.Node.Children()
		return (&IterOpt[P, R]{
			Pred: kids[0].(goohm.RuleNode),
			Term: kids[1].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "Pred":
		kids := node.Node.Children()
		return (&Pred[P, R]{
			Node: kids[0],
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for Iter_star
//
// Pred "*"
func (node *IterStar[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Iter_star")
	if v, ok := visitor.(VisitorIterStar[P, R]); ok {
		return v.VisitIterStar(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *IterStar[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptPred(visitor, payload)
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *IterStar[P, R]) AcceptPred(visitor any, payload P) (result R) {
	// Rule
	kids := node.Pred.Children()
	result = (&Pred[P, R]{
		Node: kids[0],
	}).Accept(node.Pred, visitor, payload)
	return
}

func (node *IterStar[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for Iter_plus
//
// Pred "+"
func (node *IterPlus[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Iter_plus")
	if v, ok := visitor.(VisitorIterPlus[P, R]); ok {
		return v.VisitIterPlus(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *IterPlus[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptPred(visitor, payload)
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *IterPlus[P, R]) AcceptPred(visitor any, payload P) (result R) {
	// Rule
	kids := node.Pred.Children()
	result = (&Pred[P, R]{
		Node: kids[0],
	}).Accept(node.Pred, visitor, payload)
	return
}

func (node *IterPlus[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for Iter_opt
//
// Pred "?"
func (node *IterOpt[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Iter_opt")
	if v, ok := visitor.(VisitorIterOpt[P, R]); ok {
		return v.VisitIterOpt(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *IterOpt[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptPred(visitor, payload)
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *IterOpt[P, R]) AcceptPred(visitor any, payload P) (result R) {
	// Rule
	kids := node.Pred.Children()
	result = (&Pred[P, R]{
		Node: kids[0],
	}).Accept(node.Pred, visitor, payload)
	return
}

func (node *IterOpt[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for Pred
//
// Pred
// = "~" Lex  -- not
// | "&" Lex  -- lookahead
// | Lex
func (node *Pred[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Pred")
	if v, ok := visitor.(VisitorPred[P, R]); ok {
		return v.VisitPred(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Pred[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "Pred":
		return (&Pred[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "Pred_not":
		kids := node.Node.Children()
		return (&PredNot[P, R]{
			Term: kids[0].(goohm.TerminalNode),
			Lex:  kids[1].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "Pred_lookahead":
		kids := node.Node.Children()
		return (&PredLookahead[P, R]{
			Term: kids[0].(goohm.TerminalNode),
			Lex:  kids[1].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "Lex":
		kids := node.Node.Children()
		return (&Lex[P, R]{
			Node: kids[0],
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for Pred_not
//
// "~" Lex
func (node *PredNot[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Pred_not")
	if v, ok := visitor.(VisitorPredNot[P, R]); ok {
		return v.VisitPredNot(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *PredNot[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptLex(visitor, payload)
	return
}

func (node *PredNot[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *PredNot[P, R]) AcceptLex(visitor any, payload P) (result R) {
	// Rule
	kids := node.Lex.Children()
	result = (&Lex[P, R]{
		Node: kids[0],
	}).Accept(node.Lex, visitor, payload)
	return
}

// Accept implementation for Pred_lookahead
//
// "&" Lex
func (node *PredLookahead[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Pred_lookahead")
	if v, ok := visitor.(VisitorPredLookahead[P, R]); ok {
		return v.VisitPredLookahead(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *PredLookahead[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptLex(visitor, payload)
	return
}

func (node *PredLookahead[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *PredLookahead[P, R]) AcceptLex(visitor any, payload P) (result R) {
	// Rule
	kids := node.Lex.Children()
	result = (&Lex[P, R]{
		Node: kids[0],
	}).Accept(node.Lex, visitor, payload)
	return
}

// Accept implementation for Lex
//
// Lex
// = "#" Base  -- lex
// | Base
func (node *Lex[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Lex")
	if v, ok := visitor.(VisitorLex[P, R]); ok {
		return v.VisitLex(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Lex[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "Lex":
		return (&Lex[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "Lex_lex":
		kids := node.Node.Children()
		return (&LexLex[P, R]{
			Term: kids[0].(goohm.TerminalNode),
			Base: kids[1].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "Base":
		kids := node.Node.Children()
		return (&Base[P, R]{
			Node: kids[0],
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for Lex_lex
//
// "#" Base
func (node *LexLex[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Lex_lex")
	if v, ok := visitor.(VisitorLexLex[P, R]); ok {
		return v.VisitLexLex(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexLex[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptBase(visitor, payload)
	return
}

func (node *LexLex[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *LexLex[P, R]) AcceptBase(visitor any, payload P) (result R) {
	// Rule
	kids := node.Base.Children()
	result = (&Base[P, R]{
		Node: kids[0],
	}).Accept(node.Base, visitor, payload)
	return
}

// Accept implementation for Base
//
// Base
// = ident Params? ~(ruleDescr? "=" | ":=" | "+=")  -- application
// | oneCharTerminal ".." oneCharTerminal           -- range
// | terminal                                       -- terminal
// | "(" Alt ")"                                    -- paren
func (node *Base[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Base")
	if v, ok := visitor.(VisitorBase[P, R]); ok {
		return v.VisitBase(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *Base[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "Base":
		return (&Base[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "Base_application":
		kids := node.Node.Children()
		return (&BaseApplication[P, R]{
			Ident:  kids[0].(goohm.RuleNode),
			Params: kids[1].(goohm.OptNode),
		}).Accept(node.Node, visitor, payload)
	case "Base_range":
		kids := node.Node.Children()
		return (&BaseRange[P, R]{
			OneCharTerminal1: kids[0].(goohm.RuleNode),
			Term:             kids[1].(goohm.TerminalNode),
			OneCharTerminal2: kids[2].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "Base_terminal":
		kids := node.Node.Children()
		return (&BaseTerminal[P, R]{
			Terminal: kids[0].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "Base_paren":
		kids := node.Node.Children()
		return (&BaseParen[P, R]{
			Term1: kids[0].(goohm.TerminalNode),
			Alt:   kids[1].(goohm.RuleNode),
			Term2: kids[2].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for Base_application
//
// ident Params? ~(ruleDescr? "=" | ":=" | "+=")
func (node *BaseApplication[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Base_application")
	if v, ok := visitor.(VisitorBaseApplication[P, R]); ok {
		return v.VisitBaseApplication(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *BaseApplication[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexIdent(visitor, payload)
	result = node.AcceptParams(visitor, payload)
	return
}

func (node *BaseApplication[P, R]) AcceptLexIdent(visitor any, payload P) (result R) {
	// Rule
	kids := node.Ident.Children()
	result = (&LexIdent[P, R]{
		Name: kids[0].(goohm.RuleNode),
	}).Accept(node.Ident, visitor, payload)
	return
}

func (node *BaseApplication[P, R]) AcceptParams(visitor any, payload P) (result R) {
	// Opt
	if len(node.Params.Children()) > 0 {
		n := node.Params.Children()[0]
		kids := n.Children()
		result = (&Params[P, R]{
			Term1:  kids[0].(goohm.TerminalNode),
			ListOf: kids[1].(goohm.BHorNode),
			Term2:  kids[2].(goohm.TerminalNode),
		}).Accept(n, visitor, payload)
	}
	return
}

// Accept implementation for Base_range
//
// oneCharTerminal ".." oneCharTerminal
func (node *BaseRange[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Base_range")
	if v, ok := visitor.(VisitorBaseRange[P, R]); ok {
		return v.VisitBaseRange(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *BaseRange[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexOneCharTerminal1(visitor, payload)
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptLexOneCharTerminal2(visitor, payload)
	return
}

func (node *BaseRange[P, R]) AcceptLexOneCharTerminal1(visitor any, payload P) (result R) {
	// Rule
	kids := node.OneCharTerminal1.Children()
	result = (&LexOneCharTerminal[P, R]{
		Term1:        kids[0].(goohm.TerminalNode),
		TerminalChar: kids[1].(goohm.RuleNode),
		Term2:        kids[2].(goohm.TerminalNode),
	}).Accept(node.OneCharTerminal1, visitor, payload)
	return
}

func (node *BaseRange[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *BaseRange[P, R]) AcceptLexOneCharTerminal2(visitor any, payload P) (result R) {
	// Rule
	kids := node.OneCharTerminal2.Children()
	result = (&LexOneCharTerminal[P, R]{
		Term1:        kids[0].(goohm.TerminalNode),
		TerminalChar: kids[1].(goohm.RuleNode),
		Term2:        kids[2].(goohm.TerminalNode),
	}).Accept(node.OneCharTerminal2, visitor, payload)
	return
}

// Accept implementation for Base_terminal
//
// terminal
func (node *BaseTerminal[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Base_terminal")
	if v, ok := visitor.(VisitorBaseTerminal[P, R]); ok {
		return v.VisitBaseTerminal(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *BaseTerminal[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerminal(visitor, payload)
	return
}

func (node *BaseTerminal[P, R]) AcceptLexTerminal(visitor any, payload P) (result R) {
	// Rule
	kids := node.Terminal.Children()
	result = (&LexTerminal[P, R]{
		Term1:        kids[0].(goohm.TerminalNode),
		TerminalChar: kids[1].(goohm.ListNode),
		Term2:        kids[2].(goohm.TerminalNode),
	}).Accept(node.Terminal, visitor, payload)
	return
}

// Accept implementation for Base_paren
//
// "(" Alt ")"
func (node *BaseParen[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "Base_paren")
	if v, ok := visitor.(VisitorBaseParen[P, R]); ok {
		return v.VisitBaseParen(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *BaseParen[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptAlt(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *BaseParen[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *BaseParen[P, R]) AcceptAlt(visitor any, payload P) (result R) {
	// Rule
	kids := node.Alt.Children()
	result = (&Alt[P, R]{
		NonemptyListOf: kids[0].(goohm.BHorNode),
	}).Accept(node.Alt, visitor, payload)
	return
}

func (node *BaseParen[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for ruleDescr - a rule description
//
// ruleDescr  (a rule description)
// = "(" ruleDescrText ")"
func (node *LexRuleDescr[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "ruleDescr")
	if v, ok := visitor.(VisitorLexRuleDescr[P, R]); ok {
		return v.VisitLexRuleDescr(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexRuleDescr[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptLexRuleDescrText(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *LexRuleDescr[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *LexRuleDescr[P, R]) AcceptLexRuleDescrText(visitor any, payload P) (result R) {
	// Rule
	kids := node.RuleDescrText.Children()
	result = (&LexRuleDescrText[P, R]{
		Alt: kids[0].(goohm.ListNode),
	}).Accept(node.RuleDescrText, visitor, payload)
	return
}

func (node *LexRuleDescr[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for ruleDescrText
//
// ruleDescrText
// = (~")" any)*
func (node *LexRuleDescrText[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "ruleDescrText")
	if v, ok := visitor.(VisitorLexRuleDescrText[P, R]); ok {
		return v.VisitLexRuleDescrText(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexRuleDescrText[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexAlt(visitor, payload)
	return
}

func (node *LexRuleDescrText[P, R]) AcceptLexAlt(visitor any, payload P) (result R) {
	for _, n := range node.Alt.Children() {
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	}
	return
}

// Accept implementation for caseName
//
// caseName
// = "--" (~"\n" space)* name (~"\n" space)* ("\n" | &"}")
func (node *LexCaseName[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "caseName")
	if v, ok := visitor.(VisitorLexCaseName[P, R]); ok {
		return v.VisitLexCaseName(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexCaseName[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptLexAlt1(visitor, payload)
	result = node.AcceptLexName(visitor, payload)
	result = node.AcceptLexAlt2(visitor, payload)
	result = node.AcceptLexAlt3(visitor, payload)
	return
}

func (node *LexCaseName[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *LexCaseName[P, R]) AcceptLexAlt1(visitor any, payload P) (result R) {
	for _, n := range node.Alt1.Children() {
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	}
	return
}

func (node *LexCaseName[P, R]) AcceptLexName(visitor any, payload P) (result R) {
	// Rule
	kids := node.Name.Children()
	result = (&LexName[P, R]{
		NameFirst: kids[0].(goohm.RuleNode),
		NameRest:  kids[1].(goohm.ListNode),
	}).Accept(node.Name, visitor, payload)
	return
}

func (node *LexCaseName[P, R]) AcceptLexAlt2(visitor any, payload P) (result R) {
	for _, n := range node.Alt2.Children() {
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	}
	return
}

func (node *LexCaseName[P, R]) AcceptLexAlt3(visitor any, payload P) (result R) {
	// Node
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(node.Alt3)
		}
	}
	return
}

// Accept implementation for name - a name
//
// name  (a name)
// = nameFirst nameRest*
func (node *LexName[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "name")
	if v, ok := visitor.(VisitorLexName[P, R]); ok {
		return v.VisitLexName(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexName[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexNameFirst(visitor, payload)
	result = node.AcceptLexNameRest(visitor, payload)
	return
}

func (node *LexName[P, R]) AcceptLexNameFirst(visitor any, payload P) (result R) {
	// Rule
	kids := node.NameFirst.Children()
	result = (&LexNameFirst[P, R]{
		Arg: kids[0],
	}).Accept(node.NameFirst, visitor, payload)
	return
}

func (node *LexName[P, R]) AcceptLexNameRest(visitor any, payload P) (result R) {
	for _, n := range node.NameRest.Children() {
		kids := n.Children()
		result = (&LexNameRest[P, R]{
			Arg: kids[0],
		}).Accept(n, visitor, payload)
	}
	return
}

// Accept implementation for nameFirst
//
// nameFirst
// = "_"
// | letter
func (node *LexNameFirst[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "nameFirst")
	if v, ok := visitor.(VisitorLexNameFirst[P, R]); ok {
		return v.VisitLexNameFirst(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexNameFirst[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexArg(visitor, payload)
	return
}

func (node *LexNameFirst[P, R]) AcceptLexArg(visitor any, payload P) (result R) {
	// Node
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(node.Arg)
		}
	}
	return
}

// Accept implementation for nameRest
//
// nameRest
// = "_"
// | alnum
func (node *LexNameRest[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "nameRest")
	if v, ok := visitor.(VisitorLexNameRest[P, R]); ok {
		return v.VisitLexNameRest(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexNameRest[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexArg(visitor, payload)
	return
}

func (node *LexNameRest[P, R]) AcceptLexArg(visitor any, payload P) (result R) {
	// Node
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(node.Arg)
		}
	}
	return
}

// Accept implementation for ident - an identifier
//
// ident  (an identifier)
// = name
func (node *LexIdent[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "ident")
	if v, ok := visitor.(VisitorLexIdent[P, R]); ok {
		return v.VisitLexIdent(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexIdent[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexName(visitor, payload)
	return
}

func (node *LexIdent[P, R]) AcceptLexName(visitor any, payload P) (result R) {
	// Rule
	kids := node.Name.Children()
	result = (&LexName[P, R]{
		NameFirst: kids[0].(goohm.RuleNode),
		NameRest:  kids[1].(goohm.ListNode),
	}).Accept(node.Name, visitor, payload)
	return
}

// Accept implementation for terminal
//
// terminal
// = "\"" terminalChar* "\""
func (node *LexTerminal[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "terminal")
	if v, ok := visitor.(VisitorLexTerminal[P, R]); ok {
		return v.VisitLexTerminal(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexTerminal[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptLexTerminalChar(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *LexTerminal[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *LexTerminal[P, R]) AcceptLexTerminalChar(visitor any, payload P) (result R) {
	for _, n := range node.TerminalChar.Children() {
		kids := n.Children()
		result = (&LexTerminalChar[P, R]{
			Arg: kids[0],
		}).Accept(n, visitor, payload)
	}
	return
}

func (node *LexTerminal[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for oneCharTerminal
//
// oneCharTerminal
// = "\"" terminalChar "\""
func (node *LexOneCharTerminal[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "oneCharTerminal")
	if v, ok := visitor.(VisitorLexOneCharTerminal[P, R]); ok {
		return v.VisitLexOneCharTerminal(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexOneCharTerminal[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptLexTerminalChar(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *LexOneCharTerminal[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *LexOneCharTerminal[P, R]) AcceptLexTerminalChar(visitor any, payload P) (result R) {
	// Rule
	kids := node.TerminalChar.Children()
	result = (&LexTerminalChar[P, R]{
		Arg: kids[0],
	}).Accept(node.TerminalChar, visitor, payload)
	return
}

func (node *LexOneCharTerminal[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for terminalChar
//
// terminalChar
// = escapeChar
// | ~"\\" ~"\"" ~"\n" "\u{0}".."\u{10FFFF}"
func (node *LexTerminalChar[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "terminalChar")
	if v, ok := visitor.(VisitorLexTerminalChar[P, R]); ok {
		return v.VisitLexTerminalChar(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexTerminalChar[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexArg(visitor, payload)
	return
}

func (node *LexTerminalChar[P, R]) AcceptLexArg(visitor any, payload P) (result R) {
	// Node
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(node.Arg)
		}
	}
	return
}

// Accept implementation for escapeChar - an escape sequence
//
// escapeChar  (an escape sequence)
// = "\\\\"                                     -- backslash
// | "\\\""                                     -- doubleQuote
// | "\\\'"                                     -- singleQuote
// | "\\b"                                      -- backspace
// | "\\n"                                      -- lineFeed
// | "\\r"                                      -- carriageReturn
// | "\\t"                                      -- tab
// | "\\u{" hexDigit hexDigit? hexDigit?
// hexDigit? hexDigit? hexDigit? "}"   -- unicodeCodePoint
// | "\\u" hexDigit hexDigit hexDigit hexDigit  -- unicodeEscape
// | "\\x" hexDigit hexDigit                    -- hexEscape
func (node *LexEscapeChar[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar")
	if v, ok := visitor.(VisitorLexEscapeChar[P, R]); ok {
		return v.VisitLexEscapeChar(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeChar[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "LexEscapeChar":
		return (&LexEscapeChar[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "escapeChar_backslash":
		kids := node.Node.Children()
		return (&LexEscapeCharBackslash[P, R]{
			Term: kids[0].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_doubleQuote":
		kids := node.Node.Children()
		return (&LexEscapeCharDoubleQuote[P, R]{
			Term: kids[0].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_singleQuote":
		kids := node.Node.Children()
		return (&LexEscapeCharSingleQuote[P, R]{
			Term: kids[0].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_backspace":
		kids := node.Node.Children()
		return (&LexEscapeCharBackspace[P, R]{
			Term: kids[0].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_lineFeed":
		kids := node.Node.Children()
		return (&LexEscapeCharLineFeed[P, R]{
			Term: kids[0].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_carriageReturn":
		kids := node.Node.Children()
		return (&LexEscapeCharCarriageReturn[P, R]{
			Term: kids[0].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_tab":
		kids := node.Node.Children()
		return (&LexEscapeCharTab[P, R]{
			Term: kids[0].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_unicodeCodePoint":
		kids := node.Node.Children()
		return (&LexEscapeCharUnicodeCodePoint[P, R]{
			Term1:     kids[0].(goohm.TerminalNode),
			HexDigit1: kids[1].(goohm.RuleNode),
			HexDigit2: kids[2].(goohm.OptNode),
			HexDigit3: kids[3].(goohm.OptNode),
			HexDigit4: kids[4].(goohm.OptNode),
			HexDigit5: kids[5].(goohm.OptNode),
			HexDigit6: kids[6].(goohm.OptNode),
			Term2:     kids[7].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_unicodeEscape":
		kids := node.Node.Children()
		return (&LexEscapeCharUnicodeEscape[P, R]{
			Term:      kids[0].(goohm.TerminalNode),
			HexDigit1: kids[1].(goohm.RuleNode),
			HexDigit2: kids[2].(goohm.RuleNode),
			HexDigit3: kids[3].(goohm.RuleNode),
			HexDigit4: kids[4].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	case "escapeChar_hexEscape":
		kids := node.Node.Children()
		return (&LexEscapeCharHexEscape[P, R]{
			Term:      kids[0].(goohm.TerminalNode),
			HexDigit1: kids[1].(goohm.RuleNode),
			HexDigit2: kids[2].(goohm.RuleNode),
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for escapeChar_backslash
//
// "\\\\"
func (node *LexEscapeCharBackslash[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_backslash")
	if v, ok := visitor.(VisitorLexEscapeCharBackslash[P, R]); ok {
		return v.VisitLexEscapeCharBackslash(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharBackslash[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexEscapeCharBackslash[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for escapeChar_doubleQuote
//
// "\\\""
func (node *LexEscapeCharDoubleQuote[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_doubleQuote")
	if v, ok := visitor.(VisitorLexEscapeCharDoubleQuote[P, R]); ok {
		return v.VisitLexEscapeCharDoubleQuote(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharDoubleQuote[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexEscapeCharDoubleQuote[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for escapeChar_singleQuote
//
// "\\\'"
func (node *LexEscapeCharSingleQuote[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_singleQuote")
	if v, ok := visitor.(VisitorLexEscapeCharSingleQuote[P, R]); ok {
		return v.VisitLexEscapeCharSingleQuote(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharSingleQuote[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexEscapeCharSingleQuote[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for escapeChar_backspace
//
// "\\b"
func (node *LexEscapeCharBackspace[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_backspace")
	if v, ok := visitor.(VisitorLexEscapeCharBackspace[P, R]); ok {
		return v.VisitLexEscapeCharBackspace(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharBackspace[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexEscapeCharBackspace[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for escapeChar_lineFeed
//
// "\\n"
func (node *LexEscapeCharLineFeed[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_lineFeed")
	if v, ok := visitor.(VisitorLexEscapeCharLineFeed[P, R]); ok {
		return v.VisitLexEscapeCharLineFeed(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharLineFeed[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexEscapeCharLineFeed[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for escapeChar_carriageReturn
//
// "\\r"
func (node *LexEscapeCharCarriageReturn[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_carriageReturn")
	if v, ok := visitor.(VisitorLexEscapeCharCarriageReturn[P, R]); ok {
		return v.VisitLexEscapeCharCarriageReturn(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharCarriageReturn[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexEscapeCharCarriageReturn[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for escapeChar_tab
//
// "\\t"
func (node *LexEscapeCharTab[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_tab")
	if v, ok := visitor.(VisitorLexEscapeCharTab[P, R]); ok {
		return v.VisitLexEscapeCharTab(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharTab[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexEscapeCharTab[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for escapeChar_unicodeCodePoint
//
// "\\u{" hexDigit hexDigit? hexDigit?
// hexDigit? hexDigit? hexDigit? "}"
func (node *LexEscapeCharUnicodeCodePoint[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_unicodeCodePoint")
	if v, ok := visitor.(VisitorLexEscapeCharUnicodeCodePoint[P, R]); ok {
		return v.VisitLexEscapeCharUnicodeCodePoint(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptLexHexDigit1(visitor, payload)
	result = node.AcceptLexHexDigit2(visitor, payload)
	result = node.AcceptLexHexDigit3(visitor, payload)
	result = node.AcceptLexHexDigit4(visitor, payload)
	result = node.AcceptLexHexDigit5(visitor, payload)
	result = node.AcceptLexHexDigit6(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) AcceptLexHexDigit1(visitor any, payload P) (result R) {
	// Rule
	// "unknown rule hexDigit"
	if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		v.BuiltInRule(node.HexDigit1)
	}
	return
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) AcceptLexHexDigit2(visitor any, payload P) (result R) {
	// Opt
	if len(node.HexDigit2.Children()) > 0 {
		n := node.HexDigit2.Children()[0]
		// "unknown rule hexDigit"
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	return
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) AcceptLexHexDigit3(visitor any, payload P) (result R) {
	// Opt
	if len(node.HexDigit3.Children()) > 0 {
		n := node.HexDigit3.Children()[0]
		// "unknown rule hexDigit"
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	return
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) AcceptLexHexDigit4(visitor any, payload P) (result R) {
	// Opt
	if len(node.HexDigit4.Children()) > 0 {
		n := node.HexDigit4.Children()[0]
		// "unknown rule hexDigit"
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	return
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) AcceptLexHexDigit5(visitor any, payload P) (result R) {
	// Opt
	if len(node.HexDigit5.Children()) > 0 {
		n := node.HexDigit5.Children()[0]
		// "unknown rule hexDigit"
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	return
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) AcceptLexHexDigit6(visitor any, payload P) (result R) {
	// Opt
	if len(node.HexDigit6.Children()) > 0 {
		n := node.HexDigit6.Children()[0]
		// "unknown rule hexDigit"
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	return
}

func (node *LexEscapeCharUnicodeCodePoint[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for escapeChar_unicodeEscape
//
// "\\u" hexDigit hexDigit hexDigit hexDigit
func (node *LexEscapeCharUnicodeEscape[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_unicodeEscape")
	if v, ok := visitor.(VisitorLexEscapeCharUnicodeEscape[P, R]); ok {
		return v.VisitLexEscapeCharUnicodeEscape(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharUnicodeEscape[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptLexHexDigit1(visitor, payload)
	result = node.AcceptLexHexDigit2(visitor, payload)
	result = node.AcceptLexHexDigit3(visitor, payload)
	result = node.AcceptLexHexDigit4(visitor, payload)
	return
}

func (node *LexEscapeCharUnicodeEscape[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *LexEscapeCharUnicodeEscape[P, R]) AcceptLexHexDigit1(visitor any, payload P) (result R) {
	// Rule
	// "unknown rule hexDigit"
	if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		v.BuiltInRule(node.HexDigit1)
	}
	return
}

func (node *LexEscapeCharUnicodeEscape[P, R]) AcceptLexHexDigit2(visitor any, payload P) (result R) {
	// Rule
	// "unknown rule hexDigit"
	if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		v.BuiltInRule(node.HexDigit2)
	}
	return
}

func (node *LexEscapeCharUnicodeEscape[P, R]) AcceptLexHexDigit3(visitor any, payload P) (result R) {
	// Rule
	// "unknown rule hexDigit"
	if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		v.BuiltInRule(node.HexDigit3)
	}
	return
}

func (node *LexEscapeCharUnicodeEscape[P, R]) AcceptLexHexDigit4(visitor any, payload P) (result R) {
	// Rule
	// "unknown rule hexDigit"
	if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		v.BuiltInRule(node.HexDigit4)
	}
	return
}

// Accept implementation for escapeChar_hexEscape
//
// "\\x" hexDigit hexDigit
func (node *LexEscapeCharHexEscape[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "escapeChar_hexEscape")
	if v, ok := visitor.(VisitorLexEscapeCharHexEscape[P, R]); ok {
		return v.VisitLexEscapeCharHexEscape(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexEscapeCharHexEscape[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptLexHexDigit1(visitor, payload)
	result = node.AcceptLexHexDigit2(visitor, payload)
	return
}

func (node *LexEscapeCharHexEscape[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *LexEscapeCharHexEscape[P, R]) AcceptLexHexDigit1(visitor any, payload P) (result R) {
	// Rule
	// "unknown rule hexDigit"
	if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		v.BuiltInRule(node.HexDigit1)
	}
	return
}

func (node *LexEscapeCharHexEscape[P, R]) AcceptLexHexDigit2(visitor any, payload P) (result R) {
	// Rule
	// "unknown rule hexDigit"
	if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		v.BuiltInRule(node.HexDigit2)
	}
	return
}

// Accept implementation for space
//
// space
// += comment
func (node *LexSpace[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "space")
	if v, ok := visitor.(VisitorLexSpace[P, R]); ok {
		return v.VisitLexSpace(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexSpace[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexComment(visitor, payload)
	return
}

func (node *LexSpace[P, R]) AcceptLexComment(visitor any, payload P) (result R) {
	// Rule
	kids := node.Comment.Children()
	result = (&LexComment[P, R]{
		Node: kids[0],
	}).Accept(node.Comment, visitor, payload)
	return
}

// Accept implementation for comment
//
// comment
// = "//" (~"\n" any)* &("\n" | end)  -- singleLine
// | "/*" (~"*/" any)* "*/"  -- multiLine
func (node *LexComment[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "comment")
	if v, ok := visitor.(VisitorLexComment[P, R]); ok {
		return v.VisitLexComment(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexComment[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	switch node.Node.CtorName() {
	case "LexComment":
		return (&LexComment[P, R]{
			Node: node.Node.Children()[0].(goohm.RuleNode),
		}).DefaultAccept(visitor, payload)
	case "comment_singleLine":
		kids := node.Node.Children()
		return (&LexCommentSingleLine[P, R]{
			Term: kids[0].(goohm.TerminalNode),
			Alt:  kids[1].(goohm.ListNode),
		}).Accept(node.Node, visitor, payload)
	case "comment_multiLine":
		kids := node.Node.Children()
		return (&LexCommentMultiLine[P, R]{
			Term1: kids[0].(goohm.TerminalNode),
			Alt:   kids[1].(goohm.ListNode),
			Term2: kids[2].(goohm.TerminalNode),
		}).Accept(node.Node, visitor, payload)
	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
}

// Accept implementation for comment_singleLine
//
// "//" (~"\n" any)* &("\n" | end)
func (node *LexCommentSingleLine[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "comment_singleLine")
	if v, ok := visitor.(VisitorLexCommentSingleLine[P, R]); ok {
		return v.VisitLexCommentSingleLine(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexCommentSingleLine[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	result = node.AcceptLexAlt(visitor, payload)
	return
}

func (node *LexCommentSingleLine[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *LexCommentSingleLine[P, R]) AcceptLexAlt(visitor any, payload P) (result R) {
	for _, n := range node.Alt.Children() {
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	}
	return
}

// Accept implementation for comment_multiLine
//
// "/*" (~"*/" any)* "*/"
func (node *LexCommentMultiLine[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "comment_multiLine")
	if v, ok := visitor.(VisitorLexCommentMultiLine[P, R]); ok {
		return v.VisitLexCommentMultiLine(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexCommentMultiLine[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm1(visitor, payload)
	result = node.AcceptLexAlt(visitor, payload)
	result = node.AcceptLexTerm2(visitor, payload)
	return
}

func (node *LexCommentMultiLine[P, R]) AcceptLexTerm1(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *LexCommentMultiLine[P, R]) AcceptLexAlt(visitor any, payload P) (result R) {
	for _, n := range node.Alt.Children() {
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
	}
	return
}

func (node *LexCommentMultiLine[P, R]) AcceptLexTerm2(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for tokens
//
// tokens = token*
func (node *LexTokens[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "tokens")
	if v, ok := visitor.(VisitorLexTokens[P, R]); ok {
		return v.VisitLexTokens(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexTokens[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexToken(visitor, payload)
	return
}

func (node *LexTokens[P, R]) AcceptLexToken(visitor any, payload P) (result R) {
	for _, n := range node.Token.Children() {
		kids := n.Children()
		result = (&LexToken[P, R]{
			Arg1: kids[0],
		}).Accept(n, visitor, payload)
	}
	return
}

// Accept implementation for token
//
// token = caseName | comment | ident | operator | punctuation | terminal | any
func (node *LexToken[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "token")
	if v, ok := visitor.(VisitorLexToken[P, R]); ok {
		return v.VisitLexToken(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexToken[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexArg1(visitor, payload)
	return
}

func (node *LexToken[P, R]) AcceptLexArg1(visitor any, payload P) (result R) {
	// Node
	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(node.Arg1)
		}
	}
	return
}

// Accept implementation for operator
//
// operator = "<:" | "=" | ":=" | "+=" | "*" | "+" | "?" | "~" | "&"
func (node *LexOperator[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "operator")
	if v, ok := visitor.(VisitorLexOperator[P, R]); ok {
		return v.VisitLexOperator(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexOperator[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexOperator[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

// Accept implementation for punctuation
//
// punctuation = "<" | ">" | "," | "--"
func (node *LexPunctuation[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R) {
	goohm.AssertName(this, "punctuation")
	if v, ok := visitor.(VisitorLexPunctuation[P, R]); ok {
		return v.VisitLexPunctuation(node, payload)
	}
	goohm.CheckName[VisitorGrammars[P, R]](visitor)
	return node.DefaultAccept(visitor, payload)
}

func (node *LexPunctuation[P, R]) DefaultAccept(visitor any, payload P) (result R) {
	result = node.AcceptLexTerm(visitor, payload)
	return
}

func (node *LexPunctuation[P, R]) AcceptLexTerm(visitor any, payload P) (result R) {
	// Term
	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

