// Code generated by ohmgo generate interfaces - DO NOT EDIT.
package ohm

// interfaces for grammar Ohm

// Grammars
// -- rule --
// Grammars
// = Grammar*
// ----
type VisitorGrammars[P, R any] interface {
	VisitGrammars(node *Grammars[P, R], payload P) (result R)
}

// Grammar
// -- rule --
// Grammar
// = ident SuperGrammar? "{" Rule* "}"
// ----
type VisitorGrammar[P, R any] interface {
	VisitGrammar(node *Grammar[P, R], payload P) (result R)
}

// SuperGrammar
// -- rule --
// SuperGrammar
// = "<:" ident
// ----
type VisitorSuperGrammar[P, R any] interface {
	VisitSuperGrammar(node *SuperGrammar[P, R], payload P) (result R)
}

// Rule
// -- rule --
// Rule
// = ident Formals? ruleDescr? "="  RuleBody  -- define
// | ident Formals?            ":=" OverrideRuleBody  -- override
// | ident Formals?            "+=" RuleBody  -- extend
// 
// ----
type VisitorRule[P, R any] interface {
	VisitRule(node *Rule[P, R], payload P) (result R)
}

// Rule_define
// -- rule --
// ident Formals? ruleDescr? "="  RuleBody
// ----
type VisitorRuleDefine[P, R any] interface {
	VisitRuleDefine(node *RuleDefine[P, R], payload P) (result R)
}

// Rule_override
// -- rule --
// ident Formals?            ":=" OverrideRuleBody
// ----
type VisitorRuleOverride[P, R any] interface {
	VisitRuleOverride(node *RuleOverride[P, R], payload P) (result R)
}

// Rule_extend
// -- rule --
// ident Formals?            "+=" RuleBody
// ----
type VisitorRuleExtend[P, R any] interface {
	VisitRuleExtend(node *RuleExtend[P, R], payload P) (result R)
}

// RuleBody
// -- rule --
// RuleBody
// = "|"? NonemptyListOf<TopLevelTerm, "|">
// ----
type VisitorRuleBody[P, R any] interface {
	VisitRuleBody(node *RuleBody[P, R], payload P) (result R)
}

// TopLevelTerm
// -- rule --
// TopLevelTerm
// = Seq caseName  -- inline
// | Seq
// ----
type VisitorTopLevelTerm[P, R any] interface {
	VisitTopLevelTerm(node *TopLevelTerm[P, R], payload P) (result R)
}

// TopLevelTerm_inline
// -- rule --
// Seq caseName
// ----
type VisitorTopLevelTermInline[P, R any] interface {
	VisitTopLevelTermInline(node *TopLevelTermInline[P, R], payload P) (result R)
}

// OverrideRuleBody
// -- rule --
// OverrideRuleBody
// = "|"? NonemptyListOf<OverrideTopLevelTerm, "|">
// ----
type VisitorOverrideRuleBody[P, R any] interface {
	VisitOverrideRuleBody(node *OverrideRuleBody[P, R], payload P) (result R)
}

// OverrideTopLevelTerm
// -- rule --
// OverrideTopLevelTerm
// = "..."  -- superSplice
// | TopLevelTerm
// ----
type VisitorOverrideTopLevelTerm[P, R any] interface {
	VisitOverrideTopLevelTerm(node *OverrideTopLevelTerm[P, R], payload P) (result R)
}

// OverrideTopLevelTerm_superSplice
// -- rule --
// "..."
// ----
type VisitorOverrideTopLevelTermSuperSplice[P, R any] interface {
	VisitOverrideTopLevelTermSuperSplice(node *OverrideTopLevelTermSuperSplice[P, R], payload P) (result R)
}

// Formals
// -- rule --
// Formals
// = "<" ListOf<ident, ","> ">"
// ----
type VisitorFormals[P, R any] interface {
	VisitFormals(node *Formals[P, R], payload P) (result R)
}

// Params
// -- rule --
// Params
// = "<" ListOf<Seq, ","> ">"
// ----
type VisitorParams[P, R any] interface {
	VisitParams(node *Params[P, R], payload P) (result R)
}

// Alt
// -- rule --
// Alt
// = NonemptyListOf<Seq, "|">
// ----
type VisitorAlt[P, R any] interface {
	VisitAlt(node *Alt[P, R], payload P) (result R)
}

// Seq
// -- rule --
// Seq
// = Iter*
// ----
type VisitorSeq[P, R any] interface {
	VisitSeq(node *Seq[P, R], payload P) (result R)
}

// Iter
// -- rule --
// Iter
// = Pred "*"  -- star
// | Pred "+"  -- plus
// | Pred "?"  -- opt
// | Pred
// ----
type VisitorIter[P, R any] interface {
	VisitIter(node *Iter[P, R], payload P) (result R)
}

// Iter_star
// -- rule --
// Pred "*"
// ----
type VisitorIterStar[P, R any] interface {
	VisitIterStar(node *IterStar[P, R], payload P) (result R)
}

// Iter_plus
// -- rule --
// Pred "+"
// ----
type VisitorIterPlus[P, R any] interface {
	VisitIterPlus(node *IterPlus[P, R], payload P) (result R)
}

// Iter_opt
// -- rule --
// Pred "?"
// ----
type VisitorIterOpt[P, R any] interface {
	VisitIterOpt(node *IterOpt[P, R], payload P) (result R)
}

// Pred
// -- rule --
// Pred
// = "~" Lex  -- not
// | "&" Lex  -- lookahead
// | Lex
// ----
type VisitorPred[P, R any] interface {
	VisitPred(node *Pred[P, R], payload P) (result R)
}

// Pred_not
// -- rule --
// "~" Lex
// ----
type VisitorPredNot[P, R any] interface {
	VisitPredNot(node *PredNot[P, R], payload P) (result R)
}

// Pred_lookahead
// -- rule --
// "&" Lex
// ----
type VisitorPredLookahead[P, R any] interface {
	VisitPredLookahead(node *PredLookahead[P, R], payload P) (result R)
}

// Lex
// -- rule --
// Lex
// = "#" Base  -- lex
// | Base
// ----
type VisitorLex[P, R any] interface {
	VisitLex(node *Lex[P, R], payload P) (result R)
}

// Lex_lex
// -- rule --
// "#" Base
// ----
type VisitorLexLex[P, R any] interface {
	VisitLexLex(node *LexLex[P, R], payload P) (result R)
}

// Base
// -- rule --
// Base
// = ident Params? ~(ruleDescr? "=" | ":=" | "+=")  -- application
// | oneCharTerminal ".." oneCharTerminal           -- range
// | terminal                                       -- terminal
// | "(" Alt ")"                                    -- paren
// 
// ----
type VisitorBase[P, R any] interface {
	VisitBase(node *Base[P, R], payload P) (result R)
}

// Base_application
// -- rule --
// ident Params? ~(ruleDescr? "=" | ":=" | "+=")
// ----
type VisitorBaseApplication[P, R any] interface {
	VisitBaseApplication(node *BaseApplication[P, R], payload P) (result R)
}

// Base_range
// -- rule --
// oneCharTerminal ".." oneCharTerminal
// ----
type VisitorBaseRange[P, R any] interface {
	VisitBaseRange(node *BaseRange[P, R], payload P) (result R)
}

// Base_terminal
// -- rule --
// terminal
// ----
type VisitorBaseTerminal[P, R any] interface {
	VisitBaseTerminal(node *BaseTerminal[P, R], payload P) (result R)
}

// Base_paren
// -- rule --
// "(" Alt ")"
// ----
type VisitorBaseParen[P, R any] interface {
	VisitBaseParen(node *BaseParen[P, R], payload P) (result R)
}

// ruleDescr - a rule description
// -- rule --
// ruleDescr  (a rule description)
// = "(" ruleDescrText ")"
// ----
type VisitorLexRuleDescr[P, R any] interface {
	VisitLexRuleDescr(node *LexRuleDescr[P, R], payload P) (result R)
}

// ruleDescrText
// -- rule --
// ruleDescrText
// = (~")" any)*
// ----
type VisitorLexRuleDescrText[P, R any] interface {
	VisitLexRuleDescrText(node *LexRuleDescrText[P, R], payload P) (result R)
}

// caseName
// -- rule --
// caseName
// = "--" (~"\n" space)* name (~"\n" space)* ("\n" | &"}")
// ----
type VisitorLexCaseName[P, R any] interface {
	VisitLexCaseName(node *LexCaseName[P, R], payload P) (result R)
}

// name - a name
// -- rule --
// name  (a name)
// = nameFirst nameRest*
// ----
type VisitorLexName[P, R any] interface {
	VisitLexName(node *LexName[P, R], payload P) (result R)
}

// nameFirst
// -- rule --
// nameFirst
// = "_"
// | letter
// ----
type VisitorLexNameFirst[P, R any] interface {
	VisitLexNameFirst(node *LexNameFirst[P, R], payload P) (result R)
}

// nameRest
// -- rule --
// nameRest
// = "_"
// | alnum
// ----
type VisitorLexNameRest[P, R any] interface {
	VisitLexNameRest(node *LexNameRest[P, R], payload P) (result R)
}

// ident - an identifier
// -- rule --
// ident  (an identifier)
// = name
// ----
type VisitorLexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent[P, R], payload P) (result R)
}

// terminal
// -- rule --
// terminal
// = "\"" terminalChar* "\""
// ----
type VisitorLexTerminal[P, R any] interface {
	VisitLexTerminal(node *LexTerminal[P, R], payload P) (result R)
}

// oneCharTerminal
// -- rule --
// oneCharTerminal
// = "\"" terminalChar "\""
// ----
type VisitorLexOneCharTerminal[P, R any] interface {
	VisitLexOneCharTerminal(node *LexOneCharTerminal[P, R], payload P) (result R)
}

// terminalChar
// -- rule --
// terminalChar
// = escapeChar
// | ~"\\" ~"\"" ~"\n" "\u{0}".."\u{10FFFF}"
// ----
type VisitorLexTerminalChar[P, R any] interface {
	VisitLexTerminalChar(node *LexTerminalChar[P, R], payload P) (result R)
}

// escapeChar - an escape sequence
// -- rule --
// escapeChar  (an escape sequence)
// = "\\\\"                                     -- backslash
// | "\\\""                                     -- doubleQuote
// | "\\\'"                                     -- singleQuote
// | "\\b"                                      -- backspace
// | "\\n"                                      -- lineFeed
// | "\\r"                                      -- carriageReturn
// | "\\t"                                      -- tab
// | "\\u{" hexDigit hexDigit? hexDigit?
// hexDigit? hexDigit? hexDigit? "}"   -- unicodeCodePoint
// | "\\u" hexDigit hexDigit hexDigit hexDigit  -- unicodeEscape
// | "\\x" hexDigit hexDigit                    -- hexEscape
// 
// ----
type VisitorLexEscapeChar[P, R any] interface {
	VisitLexEscapeChar(node *LexEscapeChar[P, R], payload P) (result R)
}

// escapeChar_backslash
// -- rule --
// "\\\\"
// ----
type VisitorLexEscapeCharBackslash[P, R any] interface {
	VisitLexEscapeCharBackslash(node *LexEscapeCharBackslash[P, R], payload P) (result R)
}

// escapeChar_doubleQuote
// -- rule --
// "\\\""
// ----
type VisitorLexEscapeCharDoubleQuote[P, R any] interface {
	VisitLexEscapeCharDoubleQuote(node *LexEscapeCharDoubleQuote[P, R], payload P) (result R)
}

// escapeChar_singleQuote
// -- rule --
// "\\\'"
// ----
type VisitorLexEscapeCharSingleQuote[P, R any] interface {
	VisitLexEscapeCharSingleQuote(node *LexEscapeCharSingleQuote[P, R], payload P) (result R)
}

// escapeChar_backspace
// -- rule --
// "\\b"
// ----
type VisitorLexEscapeCharBackspace[P, R any] interface {
	VisitLexEscapeCharBackspace(node *LexEscapeCharBackspace[P, R], payload P) (result R)
}

// escapeChar_lineFeed
// -- rule --
// "\\n"
// ----
type VisitorLexEscapeCharLineFeed[P, R any] interface {
	VisitLexEscapeCharLineFeed(node *LexEscapeCharLineFeed[P, R], payload P) (result R)
}

// escapeChar_carriageReturn
// -- rule --
// "\\r"
// ----
type VisitorLexEscapeCharCarriageReturn[P, R any] interface {
	VisitLexEscapeCharCarriageReturn(node *LexEscapeCharCarriageReturn[P, R], payload P) (result R)
}

// escapeChar_tab
// -- rule --
// "\\t"
// ----
type VisitorLexEscapeCharTab[P, R any] interface {
	VisitLexEscapeCharTab(node *LexEscapeCharTab[P, R], payload P) (result R)
}

// escapeChar_unicodeCodePoint
// -- rule --
// "\\u{" hexDigit hexDigit? hexDigit?
// hexDigit? hexDigit? hexDigit? "}"
// ----
type VisitorLexEscapeCharUnicodeCodePoint[P, R any] interface {
	VisitLexEscapeCharUnicodeCodePoint(node *LexEscapeCharUnicodeCodePoint[P, R], payload P) (result R)
}

// escapeChar_unicodeEscape
// -- rule --
// "\\u" hexDigit hexDigit hexDigit hexDigit
// ----
type VisitorLexEscapeCharUnicodeEscape[P, R any] interface {
	VisitLexEscapeCharUnicodeEscape(node *LexEscapeCharUnicodeEscape[P, R], payload P) (result R)
}

// escapeChar_hexEscape
// -- rule --
// "\\x" hexDigit hexDigit
// ----
type VisitorLexEscapeCharHexEscape[P, R any] interface {
	VisitLexEscapeCharHexEscape(node *LexEscapeCharHexEscape[P, R], payload P) (result R)
}

// space
// -- rule --
// space
// += comment
// ----
type VisitorLexSpace[P, R any] interface {
	VisitLexSpace(node *LexSpace[P, R], payload P) (result R)
}

// comment
// -- rule --
// comment
// = "//" (~"\n" any)* &("\n" | end)  -- singleLine
// | "/*" (~"*/" any)* "*/"  -- multiLine
// 
// ----
type VisitorLexComment[P, R any] interface {
	VisitLexComment(node *LexComment[P, R], payload P) (result R)
}

// comment_singleLine
// -- rule --
// "//" (~"\n" any)* &("\n" | end)
// ----
type VisitorLexCommentSingleLine[P, R any] interface {
	VisitLexCommentSingleLine(node *LexCommentSingleLine[P, R], payload P) (result R)
}

// comment_multiLine
// -- rule --
// "/*" (~"*/" any)* "*/"
// ----
type VisitorLexCommentMultiLine[P, R any] interface {
	VisitLexCommentMultiLine(node *LexCommentMultiLine[P, R], payload P) (result R)
}

// tokens
// -- rule --
// tokens = token*
// ----
type VisitorLexTokens[P, R any] interface {
	VisitLexTokens(node *LexTokens[P, R], payload P) (result R)
}

// token
// -- rule --
// token = caseName | comment | ident | operator | punctuation | terminal | any
// ----
type VisitorLexToken[P, R any] interface {
	VisitLexToken(node *LexToken[P, R], payload P) (result R)
}

// operator
// -- rule --
// operator = "<:" | "=" | ":=" | "+=" | "*" | "+" | "?" | "~" | "&"
// ----
type VisitorLexOperator[P, R any] interface {
	VisitLexOperator(node *LexOperator[P, R], payload P) (result R)
}

// punctuation
// -- rule --
// punctuation = "<" | ">" | "," | "--"
// ----
type VisitorLexPunctuation[P, R any] interface {
	VisitLexPunctuation(node *LexPunctuation[P, R], payload P) (result R)
}

