// Code generated by ohmgo generate types - DO NOT EDIT.
package ohm

import (
	"github.com/ohmjs/goohm"
)

// types for grammar Ohm

// Grammars
// -- rule --
// Grammars
// = Grammar*
// ----
type Grammars[P any, R any] struct {
	Grammar goohm.ListNode
}

// Grammar
// -- rule --
// Grammar
// = ident SuperGrammar? "{" Rule* "}"
// ----
type Grammar[P any, R any] struct {
	Ident        goohm.RuleNode
	SuperGrammar goohm.OptNode
	Term1        goohm.TerminalNode
	Rule         goohm.ListNode
	Term2        goohm.TerminalNode
}

// SuperGrammar
// -- rule --
// SuperGrammar
// = "<:" ident
// ----
type SuperGrammar[P any, R any] struct {
	Term  goohm.TerminalNode
	Ident goohm.RuleNode
}

// Rule
// -- rule --
// Rule
// = ident Formals? ruleDescr? "="  RuleBody  -- define
// | ident Formals?            ":=" OverrideRuleBody  -- override
// | ident Formals?            "+=" RuleBody  -- extend
// 
// ----
type Rule[P any, R any] struct {
	Node goohm.Node
}

// Rule_define
// -- rule --
// ident Formals? ruleDescr? "="  RuleBody
// ----
type RuleDefine[P any, R any] struct {
	Ident     goohm.RuleNode
	Formals   goohm.OptNode
	RuleDescr goohm.OptNode
	Term      goohm.TerminalNode
	RuleBody  goohm.RuleNode
}

// Rule_override
// -- rule --
// ident Formals?            ":=" OverrideRuleBody
// ----
type RuleOverride[P any, R any] struct {
	Ident            goohm.RuleNode
	Formals          goohm.OptNode
	Term             goohm.TerminalNode
	OverrideRuleBody goohm.RuleNode
}

// Rule_extend
// -- rule --
// ident Formals?            "+=" RuleBody
// ----
type RuleExtend[P any, R any] struct {
	Ident    goohm.RuleNode
	Formals  goohm.OptNode
	Term     goohm.TerminalNode
	RuleBody goohm.RuleNode
}

// RuleBody
// -- rule --
// RuleBody
// = "|"? NonemptyListOf<TopLevelTerm, "|">
// ----
type RuleBody[P any, R any] struct {
	Term           goohm.OptNode
	NonemptyListOf goohm.BHorNode
}

// TopLevelTerm
// -- rule --
// TopLevelTerm
// = Seq caseName  -- inline
// | Seq
// ----
type TopLevelTerm[P any, R any] struct {
	Node goohm.Node
}

// TopLevelTerm_inline
// -- rule --
// Seq caseName
// ----
type TopLevelTermInline[P any, R any] struct {
	Seq      goohm.RuleNode
	CaseName goohm.RuleNode
}

// OverrideRuleBody
// -- rule --
// OverrideRuleBody
// = "|"? NonemptyListOf<OverrideTopLevelTerm, "|">
// ----
type OverrideRuleBody[P any, R any] struct {
	Term           goohm.OptNode
	NonemptyListOf goohm.BHorNode
}

// OverrideTopLevelTerm
// -- rule --
// OverrideTopLevelTerm
// = "..."  -- superSplice
// | TopLevelTerm
// ----
type OverrideTopLevelTerm[P any, R any] struct {
	Node goohm.Node
}

// OverrideTopLevelTerm_superSplice
// -- rule --
// "..."
// ----
type OverrideTopLevelTermSuperSplice[P any, R any] struct {
	Term goohm.TerminalNode
}

// Formals
// -- rule --
// Formals
// = "<" ListOf<ident, ","> ">"
// ----
type Formals[P any, R any] struct {
	Term1  goohm.TerminalNode
	ListOf goohm.BHorNode
	Term2  goohm.TerminalNode
}

// Params
// -- rule --
// Params
// = "<" ListOf<Seq, ","> ">"
// ----
type Params[P any, R any] struct {
	Term1  goohm.TerminalNode
	ListOf goohm.BHorNode
	Term2  goohm.TerminalNode
}

// Alt
// -- rule --
// Alt
// = NonemptyListOf<Seq, "|">
// ----
type Alt[P any, R any] struct {
	NonemptyListOf goohm.BHorNode
}

// Seq
// -- rule --
// Seq
// = Iter*
// ----
type Seq[P any, R any] struct {
	Iter goohm.ListNode
}

// Iter
// -- rule --
// Iter
// = Pred "*"  -- star
// | Pred "+"  -- plus
// | Pred "?"  -- opt
// | Pred
// ----
type Iter[P any, R any] struct {
	Node goohm.Node
}

// Iter_star
// -- rule --
// Pred "*"
// ----
type IterStar[P any, R any] struct {
	Pred goohm.RuleNode
	Term goohm.TerminalNode
}

// Iter_plus
// -- rule --
// Pred "+"
// ----
type IterPlus[P any, R any] struct {
	Pred goohm.RuleNode
	Term goohm.TerminalNode
}

// Iter_opt
// -- rule --
// Pred "?"
// ----
type IterOpt[P any, R any] struct {
	Pred goohm.RuleNode
	Term goohm.TerminalNode
}

// Pred
// -- rule --
// Pred
// = "~" Lex  -- not
// | "&" Lex  -- lookahead
// | Lex
// ----
type Pred[P any, R any] struct {
	Node goohm.Node
}

// Pred_not
// -- rule --
// "~" Lex
// ----
type PredNot[P any, R any] struct {
	Term goohm.TerminalNode
	Lex  goohm.RuleNode
}

// Pred_lookahead
// -- rule --
// "&" Lex
// ----
type PredLookahead[P any, R any] struct {
	Term goohm.TerminalNode
	Lex  goohm.RuleNode
}

// Lex
// -- rule --
// Lex
// = "#" Base  -- lex
// | Base
// ----
type Lex[P any, R any] struct {
	Node goohm.Node
}

// Lex_lex
// -- rule --
// "#" Base
// ----
type LexLex[P any, R any] struct {
	Term goohm.TerminalNode
	Base goohm.RuleNode
}

// Base
// -- rule --
// Base
// = ident Params? ~(ruleDescr? "=" | ":=" | "+=")  -- application
// | oneCharTerminal ".." oneCharTerminal           -- range
// | terminal                                       -- terminal
// | "(" Alt ")"                                    -- paren
// 
// ----
type Base[P any, R any] struct {
	Node goohm.Node
}

// Base_application
// -- rule --
// ident Params? ~(ruleDescr? "=" | ":=" | "+=")
// ----
type BaseApplication[P any, R any] struct {
	Ident  goohm.RuleNode
	Params goohm.OptNode
}

// Base_range
// -- rule --
// oneCharTerminal ".." oneCharTerminal
// ----
type BaseRange[P any, R any] struct {
	OneCharTerminal1 goohm.RuleNode
	Term             goohm.TerminalNode
	OneCharTerminal2 goohm.RuleNode
}

// Base_terminal
// -- rule --
// terminal
// ----
type BaseTerminal[P any, R any] struct {
	Terminal goohm.RuleNode
}

// Base_paren
// -- rule --
// "(" Alt ")"
// ----
type BaseParen[P any, R any] struct {
	Term1 goohm.TerminalNode
	Alt   goohm.RuleNode
	Term2 goohm.TerminalNode
}

// ruleDescr - a rule description
// -- rule --
// ruleDescr  (a rule description)
// = "(" ruleDescrText ")"
// ----
type LexRuleDescr[P any, R any] struct {
	Term1         goohm.TerminalNode
	RuleDescrText goohm.RuleNode
	Term2         goohm.TerminalNode
}

// ruleDescrText
// -- rule --
// ruleDescrText
// = (~")" any)*
// ----
type LexRuleDescrText[P any, R any] struct {
	Alt goohm.ListNode
}

// caseName
// -- rule --
// caseName
// = "--" (~"\n" space)* name (~"\n" space)* ("\n" | &"}")
// ----
type LexCaseName[P any, R any] struct {
	Term goohm.TerminalNode
	Alt1 goohm.ListNode
	Name goohm.RuleNode
	Alt2 goohm.ListNode
	Alt3 goohm.Node
}

// name - a name
// -- rule --
// name  (a name)
// = nameFirst nameRest*
// ----
type LexName[P any, R any] struct {
	NameFirst goohm.RuleNode
	NameRest  goohm.ListNode
}

// nameFirst
// -- rule --
// nameFirst
// = "_"
// | letter
// ----
type LexNameFirst[P any, R any] struct {
	Arg goohm.Node
}

// nameRest
// -- rule --
// nameRest
// = "_"
// | alnum
// ----
type LexNameRest[P any, R any] struct {
	Arg goohm.Node
}

// ident - an identifier
// -- rule --
// ident  (an identifier)
// = name
// ----
type LexIdent[P any, R any] struct {
	Name goohm.RuleNode
}

// terminal
// -- rule --
// terminal
// = "\"" terminalChar* "\""
// ----
type LexTerminal[P any, R any] struct {
	Term1        goohm.TerminalNode
	TerminalChar goohm.ListNode
	Term2        goohm.TerminalNode
}

// oneCharTerminal
// -- rule --
// oneCharTerminal
// = "\"" terminalChar "\""
// ----
type LexOneCharTerminal[P any, R any] struct {
	Term1        goohm.TerminalNode
	TerminalChar goohm.RuleNode
	Term2        goohm.TerminalNode
}

// terminalChar
// -- rule --
// terminalChar
// = escapeChar
// | ~"\\" ~"\"" ~"\n" "\u{0}".."\u{10FFFF}"
// ----
type LexTerminalChar[P any, R any] struct {
	Arg goohm.Node
}

// escapeChar - an escape sequence
// -- rule --
// escapeChar  (an escape sequence)
// = "\\\\"                                     -- backslash
// | "\\\""                                     -- doubleQuote
// | "\\\'"                                     -- singleQuote
// | "\\b"                                      -- backspace
// | "\\n"                                      -- lineFeed
// | "\\r"                                      -- carriageReturn
// | "\\t"                                      -- tab
// | "\\u{" hexDigit hexDigit? hexDigit?
// hexDigit? hexDigit? hexDigit? "}"   -- unicodeCodePoint
// | "\\u" hexDigit hexDigit hexDigit hexDigit  -- unicodeEscape
// | "\\x" hexDigit hexDigit                    -- hexEscape
// 
// ----
type LexEscapeChar[P any, R any] struct {
	Node goohm.Node
}

// escapeChar_backslash
// -- rule --
// "\\\\"
// ----
type LexEscapeCharBackslash[P any, R any] struct {
	Term goohm.TerminalNode
}

// escapeChar_doubleQuote
// -- rule --
// "\\\""
// ----
type LexEscapeCharDoubleQuote[P any, R any] struct {
	Term goohm.TerminalNode
}

// escapeChar_singleQuote
// -- rule --
// "\\\'"
// ----
type LexEscapeCharSingleQuote[P any, R any] struct {
	Term goohm.TerminalNode
}

// escapeChar_backspace
// -- rule --
// "\\b"
// ----
type LexEscapeCharBackspace[P any, R any] struct {
	Term goohm.TerminalNode
}

// escapeChar_lineFeed
// -- rule --
// "\\n"
// ----
type LexEscapeCharLineFeed[P any, R any] struct {
	Term goohm.TerminalNode
}

// escapeChar_carriageReturn
// -- rule --
// "\\r"
// ----
type LexEscapeCharCarriageReturn[P any, R any] struct {
	Term goohm.TerminalNode
}

// escapeChar_tab
// -- rule --
// "\\t"
// ----
type LexEscapeCharTab[P any, R any] struct {
	Term goohm.TerminalNode
}

// escapeChar_unicodeCodePoint
// -- rule --
// "\\u{" hexDigit hexDigit? hexDigit?
// hexDigit? hexDigit? hexDigit? "}"
// ----
type LexEscapeCharUnicodeCodePoint[P any, R any] struct {
	Term1     goohm.TerminalNode
	HexDigit1 goohm.RuleNode
	HexDigit2 goohm.OptNode
	HexDigit3 goohm.OptNode
	HexDigit4 goohm.OptNode
	HexDigit5 goohm.OptNode
	HexDigit6 goohm.OptNode
	Term2     goohm.TerminalNode
}

// escapeChar_unicodeEscape
// -- rule --
// "\\u" hexDigit hexDigit hexDigit hexDigit
// ----
type LexEscapeCharUnicodeEscape[P any, R any] struct {
	Term      goohm.TerminalNode
	HexDigit1 goohm.RuleNode
	HexDigit2 goohm.RuleNode
	HexDigit3 goohm.RuleNode
	HexDigit4 goohm.RuleNode
}

// escapeChar_hexEscape
// -- rule --
// "\\x" hexDigit hexDigit
// ----
type LexEscapeCharHexEscape[P any, R any] struct {
	Term      goohm.TerminalNode
	HexDigit1 goohm.RuleNode
	HexDigit2 goohm.RuleNode
}

// space
// -- rule --
// space
// += comment
// ----
type LexSpace[P any, R any] struct {
	Comment goohm.RuleNode
}

// comment
// -- rule --
// comment
// = "//" (~"\n" any)* &("\n" | end)  -- singleLine
// | "/*" (~"*/" any)* "*/"  -- multiLine
// 
// ----
type LexComment[P any, R any] struct {
	Node goohm.Node
}

// comment_singleLine
// -- rule --
// "//" (~"\n" any)* &("\n" | end)
// ----
type LexCommentSingleLine[P any, R any] struct {
	Term goohm.TerminalNode
	Alt  goohm.ListNode
}

// comment_multiLine
// -- rule --
// "/*" (~"*/" any)* "*/"
// ----
type LexCommentMultiLine[P any, R any] struct {
	Term1 goohm.TerminalNode
	Alt   goohm.ListNode
	Term2 goohm.TerminalNode
}

// tokens
// -- rule --
// tokens = token*
// ----
type LexTokens[P any, R any] struct {
	Token goohm.ListNode
}

// token
// -- rule --
// token = caseName | comment | ident | operator | punctuation | terminal | any
// ----
type LexToken[P any, R any] struct {
	Arg1 goohm.Node
}

// operator
// -- rule --
// operator = "<:" | "=" | ":=" | "+=" | "*" | "+" | "?" | "~" | "&"
// ----
type LexOperator[P any, R any] struct {
	Term goohm.TerminalNode
}

// punctuation
// -- rule --
// punctuation = "<" | ">" | "," | "--"
// ----
type LexPunctuation[P any, R any] struct {
	Term goohm.TerminalNode
}

