package ruleast

import (
	"context"
	"fmt"
	"os"
	"runtime"
	"strings"

	"github.com/ohmjs/goohm"
	"github.com/ohmjs/ohmgo/utils"
	"github.com/samber/lo"
)

type genAcceptsCmd struct {
	GenCmd     genCmd `opts:"mode=embedded"`
	OutputFile string
	gmrsAst    GrammarsNode
}

func (vc *genAcceptsCmd) outf(format string, a ...any) {
	_, file, line, _ := runtime.Caller(1) // for line numbers to be correct when SuffixOutfLineNos is true
	parts := strings.Split(file, "/")
	parts = parts[len(parts)-2:]
	file = strings.Join(parts, "/")
	callerLine := fmt.Sprintf("%s:%d", file, line)
	f0 := format
	if vc.GenCmd.SuffixOutfLineNos {
		f0 = strings.ReplaceAll(format, "\n", fmt.Sprintf(" // %%[%d]s\n", len(a)+1))
		a = append(a, callerLine)
	}
	fmt.Fprintf(vc.GenCmd.sbldr, f0, a...)
}

func NewGenAcceptsCmd() *genAcceptsCmd {
	return &genAcceptsCmd{
		GenCmd: genCmd{
			GoRuntimeImport:   "github.com/ohmjs/goohm",
			GoRuntimePackage:  "goohm",
			sbldr:             &strings.Builder{},
			SuffixOutfLineNos: true,
		},
	}
}

func (vc *genAcceptsCmd) Run() error {
	if vc.GenCmd.Grammar[:1] == "@" {
		barr, err := os.ReadFile(vc.GenCmd.Grammar[1:])
		if err != nil {
			return fmt.Errorf("Error reading grammar file. %[1]v", err)
		}
		vc.GenCmd.Grammar = string(barr)
	}
	out, err := vc.Process()
	if err != nil {
		return err
	}
	if vc.OutputFile == "-" {
		fmt.Printf("%[1]s\n", out)
		return nil
	}
	fi, err := os.Create(vc.OutputFile)
	if err != nil {
		return fmt.Errorf("error creating file %[1]w", err)
	}
	defer fi.Close()
	_, err = fi.WriteString(out)
	if err != nil {
		return fmt.Errorf("error writing file %[1]w", err)
	}
	return nil
}

func (vc *genAcceptsCmd) Process() (string, error) {
	ctx := context.Background()
	var (
		gmr  *goohm.Grammar
		mr   *goohm.MatchResult
		err  error
		root goohm.Node
	)
	if gmr, err = goohm.NewGrammar(ctx, utils.OhmGrammarWasmBytes()); err != nil {
		return "", fmt.Errorf("creating grammar: %[1]v", err)
	}
	defer gmr.Close()
	if mr, err = gmr.Match(vc.GenCmd.Grammar); err != nil {
		return "", fmt.Errorf("matching: %[1]v", err)
	}
	defer mr.Close()
	if !mr.Succeeded() {
		return "", fmt.Errorf("match failed")
	}
	if root, err = mr.GetCstRoot(); err != nil {
		return "", fmt.Errorf("Error getting cst root. %[1]v", err)
	}
	gmrsAst, err := NewBuildGrammars(root).BuildRuleAst(root)
	if err != nil {
		return "", fmt.Errorf("Error building rule ast. %[1]v", err)
	}
	if len(gmrsAst.Gmr_names) > 1 {
		if vc.GenCmd.GrammarName == "" {
			return "", fmt.Errorf("For files with multiple grammars, the --grammar-name flag is required")
		}
	}
	if vc.GenCmd.GrammarName != "" {
		if _, ok := gmrsAst.Grammars[vc.GenCmd.GrammarName]; !ok {
			return "", fmt.Errorf("grammar-name not found. Asked for '%s', grammar names are '%v'", vc.GenCmd.GrammarName, gmrsAst.Gmr_names)
		}
	}
	vc.gmrsAst = *gmrsAst
	vc.gmrsAst.GenGoAccepts(vc)
	return vc.GenCmd.sbldr.String(), nil
}

func (gmrs GrammarsNode) GenGoAccepts(vc *genAcceptsCmd) {
	if vc.GenCmd.GoTypePackage == "" {
		vc.GenCmd.GoTypePackage = strings.ToLower(gmrs.Gmr_names[0])
	}
	vc.outf(`// Code generated by ohmgo generate accepts - DO NOT EDIT.
package %[1]s

import (
	"%[2]s"
)

`, vc.GenCmd.GoTypePackage, vc.GenCmd.GoRuntimeImport)
	if vc.GenCmd.GrammarName != "" {
		gmr := gmrs.Grammars[vc.GenCmd.GrammarName]
		gmr.GenGoAccepts(vc)
		vc.outf(`// accepts for grammar %[1]s

`, gmr.Name)
		return
	}
	for _, gname := range gmrs.Gmr_names {
		vc.outf(`// accepts for grammar %[1]s

`, gname)
		gmr := gmrs.Grammars[gname]
		gmr.GenGoAccepts(vc)
	}
}

func (gmr GrammarNode) GenGoAccepts(vc *genAcceptsCmd) {
	vc.outf(`// TODO for grammar %[1]s, implement Make func for starting rule %[2]s

`,
		gmr.Name,
		gmr.Rule_names[0],
	)
	for _, rname := range gmr.Rule_names {
		rule := gmr.Rules[rname]
		branch := rule.GetBranch()
		vc.outf(`// Accept implementation for %[1]s%[2]s
//
`,
			branch.RuleName(),
			branch.Descr(" - ", ""),
		)
		for _, line := range branch.Source() {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			vc.outf(`// %[1]s
`,
				line,
			)
		}
		type_prefix := "Visitor"
		method_prefix := "Visit"
		if _, is_case := rule.Cast_case_rule(); is_case {
			type_prefix = "Switcher"
			method_prefix = "Switch"
		}
		vc.outf(`func (node *%[1]s[P, R]) Accept(this goohm.Node, visitor any, payload P) (result R, err error) {
	%[2]s.AssertName(this, "%[3]s")
	if v, ok := visitor.(%[4]s_%[1]s[P, R]); ok {
		v.%[5]s%[1]s(node)
		return
	}
	if v, ok := visitor.(%[4]sE_%[1]s[P, R]); ok {
		err = v.%[5]s%[1]s(node)
		return
	}
	if v, ok := visitor.(%[4]sP_%[1]s[P, R]); ok {
		v.%[5]s%[1]s(node, payload)
		return
	}
	if v, ok := visitor.(%[4]sPE_%[1]s[P, R]); ok {
		err = v.%[5]s%[1]s(node, payload)
		return
	}
	if v, ok := visitor.(%[4]sR_%[1]s[P, R]); ok {
		result = v.%[5]s%[1]s(node)
		return
	}
	if v, ok := visitor.(%[4]sRE_%[1]s[P, R]); ok {
		result, err = v.%[5]s%[1]s(node)
		return
	}
	if v, ok := visitor.(%[4]sPR_%[1]s[P, R]); ok {
		result = v.%[5]s%[1]s(node, payload)
		return
	}
	if v, ok := visitor.(%[4]sPRE_%[1]s[P, R]); ok {
		result, err = v.%[5]s%[1]s(node, payload)
		return
	}
	goohm.TypeCheckMethod[P, R](visitor, "%[1]s")
	return node.DefaultAccept(visitor, payload)
}

`,
			branch.TypeName(),
			vc.GenCmd.GoRuntimePackage,
			branch.RuleName(),
			type_prefix,
			method_prefix,
		)
		branch.GenGoAccepts(vc, gmr.Name)
	}
}

func (node VirtRuleNode) GenGoAccepts(vc *genAcceptsCmd, gmr_name string) {
	node0 := node.Node
	node0._BareRuleNode.Name = node.TypeName()
	node0.GenGoAccepts(vc, gmr_name)
}

func (node BareRuleNode) GenGoAccepts(vc *genAcceptsCmd, gmr_name string) {
	vc.outf(`func (node *%[1]s[P, R]) DefaultAccept(visitor any, payload P) (result R, err error) {
`,
		node.TypeName(),
	)
	longest := lo.MaxBy(node.Args, func(a, b NamedArgNode) bool {
		return len(a.Name) > len(b.Name)
	})
	for _, arg := range node.Args {
		padding := strings.Repeat(" ", len(longest.Name)-len(arg.Name))
		vc.outf(`	result, err =node.Accept%[1]s(visitor, payload)
`,
			r2name(arg.Name),
			padding,
			arg.Node.GetBranch().GoType(vc.GenCmd.GoRuntimePackage),
		)
	}
	vc.outf(`	return
}

`)
	for _, arg := range node.Args {
		vc.outf(`func (node *%[1]s[P, R]) Accept%[2]s(visitor any, payload P) (result R, err error) {
`,
			node.TypeName(),
			r2name(arg.Name),
		)
		arg.Node.GetBranch().GenGoLeafAccepts(vc, gmr_name, arg.Name)
		vc.outf(`	return
}

`)
	}
}

func (node CasesRuleNode) GenGoAccepts(vc *genAcceptsCmd, gmr_name string) {
	vc.outf(`func (node *%[1]s[P, R]) DefaultAccept(visitor any, payload P) (result R, err error) {
	switch node.Node.CtorName() {
	case "%[1]s":
		return (&%[1]s[P, R]{
			Node: node.Node.Children()[0].(%[2]s.RuleNode),
		}).DefaultAccept(visitor, payload)
`,
		node.TypeName(),
		vc.GenCmd.GoRuntimePackage,
	)
	gmr, ok := vc.gmrsAst.Grammars[gmr_name]
	if !ok {
		panic(fmt.Errorf("unknown grammar '%[1]s'", gmr_name))
	}
	// inline cases
	for _, case0 := range node.Cases {
		virt_rule_name := node.RuleName() + "_" + case0.Case_name
		virt_type_name := r2name(node.TypeName()) + upper1st(case0.Case_name)
		rule, ok := gmr.Rules[virt_rule_name]

		// 	vc.outf( `	{
		// 		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		// 			v.BuiltInRule(node.%[1]s)
		// 		}
		// 	}
		// `,
		// 		upper1st(name),
		// 	)

		if !ok {
			panic(fmt.Errorf("unknown rule '%[1]s'", virt_rule_name))
		}
		vc.outf(`	case "%[1]s":
		kids := node.Node.Children()
		return (&%[2]s[P, R]{
`,
			virt_rule_name,
			virt_type_name,
		)
		rule.GetBranch().GenGoLeafInstAccepts(vc, 3)
		vc.outf(`		}).Accept(node.Node, visitor, payload)
`)
	}
	// bare cases
	if len(node.Args) > 1 {
		// todo
	}
	for _, arg0 := range node.Args {
		vc.outf(`	case "%[1]s":
`,
			arg0.Name,
		)
		name := arg0.Name
		b := arg0.Node.GetBranch()
		b.GenGoRuleNodeCaseAccepts(vc, gmr_name, name)
		// 		// todo - this is not always true
		// 		n, ok0 := arg0.Node.GetBranch().(NontNode)
		// 		if !ok0 {
		// 			panic(fmt.Errorf(
		// 				"arg0.Node.Branch is not a RuleNode (NontNode). NodeName '%s' ArgName '%s' Type %T",
		// 				node.Name,
		// 				name,
		// 				arg0.Node.GetBranch(),
		// 			))
		// 		}
		// 		rule, ok := gmr.Rules[n.Rule]
		// 		if !ok {
		// 			panic(fmt.Errorf("unknown rule %[1]s", name))
		// 		}
		// 		vc.outf(`		kids := node.Node.Children()
		// 		return (&%[1]s[P, R]{
		// `,
		// 			r2name(name),
		// 		)
		// 		rule.GetBranch().GenGoLeafInstAccepts(vc, 3)
		// 		vc.outf(`		}).Accept(node.Node, visitor, payload)
		// `,
		// 		)
	}
	// default
	vc.outf(`	default:
		panic("unexpected " + node.Node.CtorName())
	} // end switch
`)
	vc.outf(`}

`)
}

func (n NodeArgNode) GenGoRuleNodeCaseAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	vc.outf(`		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(node.%[1]s)
		}
		return
`,
		// upper1st(name),
		"Node",
	)
}
func (n RuleArgNode) GenGoRuleNodeCaseAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	rule, ok := vc.gmrsAst.Grammars[gmr_name].Rules[name]
	if !ok {
		vc.outf(`		// unknown rule '%[1]s' 
`, name)
		return
		// panic(fmt.Errorf("unknown rule '%[1]s'", name))
	}
	vc.outf(`		kids := node.Node.Children()
		return (&%[1]s[P, R]{
`,
		r2name(name),
	)
	rule.GetBranch().GenGoLeafInstAccepts(vc, 3)
	vc.outf(`		}).Accept(node.Node, visitor, payload)
`,
	)
}
func (n TermArgNode) GenGoRuleNodeCaseAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	panic("not implemented")
}
func (n ListArgNode) GenGoRuleNodeCaseAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	panic("not implemented")
}
func (n OptArgNode) GenGoRuleNodeCaseAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	panic("not implemented")
}
func (n BuiltinHorArgNode) GenGoRuleNodeCaseAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	panic("not implemented")
}

func (n NodeArgNode) GenGoLeafAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	vc.outf(`	// Node
`)
	vc.outf(`	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(node.%[1]s)
		}
	}
`,
		upper1st(name),
	)
}

func (n RuleArgNode) GenGoLeafAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	vc.outf(`	// Rule
`)
	gmr, ok := vc.gmrsAst.Grammars[gmr_name]
	if !ok {
		panic(fmt.Errorf("unknown grammar %[1]s", gmr_name))
	}
	rule, ok := gmr.Rules[n.Rule]
	if !ok {
		vc.outf(`	// "unknown rule %[1]s"
	if v, ok := visitor.(goohm.BuiltinVisitor); ok {
		v.BuiltInRule(node.%[2]s)
	}
`,
			n.Rule,
			upper1st(name),
		)
		return
	}
	vc.outf(`	kids := node.%[1]s.Children()
	result, err = (&%[2]s[P, R]{
`,
		upper1st(name),
		rule.GetBranch().TypeName(),
	)
	rule.GetBranch().GenGoLeafInstAccepts(vc, 2)
	// rule.GetBranch().
	vc.outf(`	}).Accept(node.%[1]s, visitor, payload)
`,
		upper1st(name),
	)
}

func (n TermArgNode) GenGoLeafAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	vc.outf(`	// Term
`)
	vc.outf(`	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(node.%[1]s)
	}
`,
		upper1st(name))
}

func (n ListArgNode) GenGoLeafAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	vc.outf(`	for _, n := range node.%[1]s.Children() {
`,
		upper1st(name),
	)
	Handle_ArgNode[any](
		n.Elem,
		func(nobj NodeArgNode) any {
			vc.outf(`	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
`,
			)
			return nil
		},
		func(rulenode RuleArgNode) any {
			gmr, ok := vc.gmrsAst.Grammars[gmr_name]
			if !ok {
				panic(fmt.Errorf("unknown grammar %[1]s", gmr_name))
			}
			rule, ok := gmr.Rules[rulenode.Rule]
			if !ok {
				vc.outf(`	// "unknown rule %[1]s"
`,
					rulenode.Rule,
				)
				return nil
			}
			Handle_RuleNode[any](
				rule,
				func(bare_rule BareRuleNode) any {
					vc.outf(`		kids := n.Children()
		result, err = (&%[1]s[P, R]{
`,
						bare_rule.TypeName(),
					)
					bare_rule.GenGoLeafInstAccepts(vc, 3)
					vc.outf(`		}).Accept(n, visitor, payload)
`,
					// upper1st(name),
					)
					return nil
				},
				func(virt_rule VirtRuleNode) any {
					panic("shouldn't get here")
				},
				func(case_rule CasesRuleNode) any {
					vc.outf(`		result, err =(&%[1]s[P, R]{
			Node: n,
				}).Accept(n, visitor, payload)
`,
						upper1st(case_rule.Name),
					)
					return nil
				},
				nil,
			)
			return nil
		},
		func(term TermArgNode) any {
			vc.outf(`	if v, ok := visitor.(goohm.TerminalVisitor); ok {
		v.Terminal(n)
	}
`,
			)
			return nil

		},
		func(list ListArgNode) any {
			panic("should not be possible")
		},
		func(opt OptArgNode) any {
			panic("should not be possible")
		},
		func(bhor BuiltinHorArgNode) any {
			vc.outf(`	panic("not implemented - why would you do this?")
`,
			)
			return nil
		},
		nil,
	)
	vc.outf(`	}
`,
	)
}

func (n OptArgNode) GenGoLeafAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	vc.outf(`	// Opt
`)
	vc.outf(`	if len(node.%[1]s.Children()) > 0 {
		n := node.%[1]s.Children()[0]
`,
		upper1st(name),
	)
	Handle_ArgNode[any](
		n.Elem,
		func(nobj NodeArgNode) any {
			vc.outf(`	{
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
	}
`,
			)
			return nil
		},
		func(rulenode RuleArgNode) any {
			gmr, ok := vc.gmrsAst.Grammars[gmr_name]
			if !ok {
				panic(fmt.Errorf("unknown grammar %[1]s", gmr_name))
			}
			rule, ok := gmr.Rules[rulenode.Rule]
			if !ok {

				vc.outf(`		// "unknown rule %[1]s"
		if v, ok := visitor.(goohm.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
`,
					rulenode.Rule,
				)
				return nil
			}
			Handle_RuleNode[any](
				rule,
				func(bare_rule BareRuleNode) any {
					vc.outf(`		kids := n.Children()
		result, err =(&%[1]s[P, R]{
`,
						bare_rule.TypeName(),
					)
					bare_rule.GenGoLeafInstAccepts(vc, 3)
					vc.outf(`		}).Accept(n, visitor, payload)
`,
					// upper1st(name),
					)
					return nil
				},
				func(virt_rule VirtRuleNode) any {
					panic("shouldn't get here")
				},
				func(case_rule CasesRuleNode) any {
					vc.outf(`		result, err =(&%[1]s[P, R]{
			Node: n,
				}).Accept(n, visitor, payload)
`,
						upper1st(case_rule.Name),
					)
					return nil
				},
				nil,
			)
			return nil
		},
		func(term TermArgNode) any {
			vc.outf(`		if v, ok := visitor.(goohm.TerminalVisitor); ok {
			v.Terminal(n.(%[1]s.TerminalNode))
		}
`,
				vc.GenCmd.GoRuntimePackage,
			)
			return nil

		},
		func(list ListArgNode) any {
			panic("should not be possible")
		},
		func(opt OptArgNode) any {
			panic("should not be possible")
		},
		func(bhor BuiltinHorArgNode) any {
			vc.outf(`	panic("not implemented - why would you do this?")
`,
			)
			return nil
		},
		nil,
	)
	vc.outf(`	}
`,
	)
}

func (n BuiltinHorArgNode) GenGoLeafAccepts(vc *genAcceptsCmd, gmr_name string, name string) {
	vc.outf(`	// BuiltinHOR
`)
	vc.outf(`	// %[1]s
`,
		n.Elem.Name,
	)
	n.Elem.Node.GetBranch().GenGoBHORCallback(vc, gmr_name, "fn_elem")
	n.Sep.Node.GetBranch().GenGoBHORCallback(vc, gmr_name, "fn_sep")
	vc.outf(`	goohm.AcceptBuiltinHOR(node.%[1]s, fn_elem, fn_sep)
`,
		n.List_type,
	)
}

func (NodeArgNode) GenGoBHORCallback(vc *genAcceptsCmd, gmr_name string, fname string) {
	vc.outf(`	%[1]s := func(n %[2]s.Node) (result R) {
		if v, ok := visitor.(%[2]s.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
		return
	}
`,
		fname,
		vc.GenCmd.GoRuntimePackage,
	)
}
func (rulenode RuleArgNode) GenGoBHORCallback(vc *genAcceptsCmd, gmr_name string, fname string) {
	gmr, ok := vc.gmrsAst.Grammars[gmr_name]
	if !ok {
		panic(fmt.Errorf("unknown grammar %[1]s", gmr_name))
	}
	rule, ok := gmr.Rules[rulenode.Rule]
	if !ok {
		vc.outf(`	%[1]s := func(n %[2]s.Node) (result R) {
		if v, ok := visitor.(%[2]s.BuiltinVisitor); ok {
			v.BuiltInRule(n)
		}
		return
	}
`,
			fname,
			vc.GenCmd.GoRuntimePackage,
		)
		return
	}
	vc.outf(`	%[1]s := func(n %[2]s.Node) (result R) {
		kids := n.Children()
		result, err =(&%[3]s[P, R]{
`,
		fname,
		vc.GenCmd.GoRuntimePackage,
		r2name(rulenode.Rule),
	)
	rule.GetBranch().GenGoLeafInstAccepts(vc, 3)
	vc.outf(`		}).Accept(n, visitor, payload)
		return
	}
`,
	)
}
func (TermArgNode) GenGoBHORCallback(vc *genAcceptsCmd, gmr_name string, fname string) {
	vc.outf(`	%[1]s := func(n %[2]s.Node) (result R) {
		if v, ok := visitor.(%[2]s.TerminalVisitor); ok {
			v.Terminal(n.(%[2]s.TerminalNode))
		}
		return
	}
`,
		fname,
		vc.GenCmd.GoRuntimePackage,
	)
}
func (n ListArgNode) GenGoBHORCallback(vc *genAcceptsCmd, gmr_name string, fname string) {
	vc.outf(`	%[1]s := func(n %[2]s.Node) (result R) {
		panic("not implemented")
	}
`,
		fname,
		vc.GenCmd.GoRuntimePackage,
	)
}
func (OptArgNode) GenGoBHORCallback(vc *genAcceptsCmd, gmr_name string, fname string) {
	vc.outf(`	%[1]s := func(n %[2]s.Node) (result R) {
		panic("not implemented")
	}
`,
		fname,
		vc.GenCmd.GoRuntimePackage,
	)
}
func (BuiltinHorArgNode) GenGoBHORCallback(vc *genAcceptsCmd, gmr_name string, fname string) {
	vc.outf(`	%[1]s := func(n %[2]s.Node) (result R) {
		panic("not implemented")
	}
`,
		fname,
		vc.GenCmd.GoRuntimePackage,
	)
}

func (node VirtRuleNode) GenGoLeafInstAccepts(vc *genAcceptsCmd, tabs int) {
	node.Node.GenGoLeafInstAccepts(vc, tabs)
}

func (node BareRuleNode) GenGoLeafInstAccepts(vc *genAcceptsCmd, tabs int) {
	longest := lo.MaxBy(node.Args, func(a, b NamedArgNode) bool {
		return len(a.Name) > len(b.Name)
	})
	for i, arg := range node.Args {
		padding := strings.Repeat(" ", len(longest.Name)-len(arg.Name))
		type_cast := arg.Node.GetBranch().GoType(vc.GenCmd.GoRuntimePackage)
		if type_cast == vc.GenCmd.GoRuntimePackage+".Node" {
			type_cast = ""
		} else {
			type_cast = ".(" + type_cast + ")"
		}
		vc.outf(`%[1]s%[2]s: %[3]skids[%[4]d]%[5]s,
`,
			strings.Repeat("\t", tabs),
			upper1st(arg.Name),
			padding,
			i,
			type_cast,
		)
	}
}

func (node CasesRuleNode) GenGoLeafInstAccepts(vc *genAcceptsCmd, tabs int) {
	vc.outf(`%[1]s%[2]s: kids[0],
`,
		strings.Repeat("\t", tabs),
		"Node",
		// vc.GoRuntimePackage+".Node",
	)
}
