package ruleast

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/ohmjs/goohm"
	"github.com/ohmjs/ohmgo/utils"
)

type genInterfaceCmd struct {
	GenCmd     genCmd `opts:"mode=embedded"`
	OutputFile string
}

func NewGenInterfaceCmd() *genInterfaceCmd {
	return &genInterfaceCmd{
		GenCmd: genCmd{
			GoRuntimeImport:  "github.com/ohmjs/goohm",
			GoRuntimePackage: "goohm",
			sbldr:            &strings.Builder{},
		},
	}
}

func (vc *genInterfaceCmd) Run() error {
	if vc.GenCmd.Grammar[:1] == "@" {
		barr, err := os.ReadFile(vc.GenCmd.Grammar[1:])
		if err != nil {
			return fmt.Errorf("Error reading grammar file. %v", err)
		}
		vc.GenCmd.Grammar = string(barr)
	}
	out, err := vc.Process()
	if err != nil {
		return err
	}
	if vc.OutputFile == "-" {
		fmt.Printf("%s\n", out)
		return nil
	}
	fi, err := os.Create(vc.OutputFile)
	if err != nil {
		return fmt.Errorf("error creating file %w", err)
	}
	defer fi.Close()
	_, err = fi.WriteString(out)
	if err != nil {
		return fmt.Errorf("error writing file %w", err)
	}
	return nil
}

func (vc *genInterfaceCmd) Process() (string, error) {
	ctx := context.Background()
	var (
		gmr  *goohm.Grammar
		mr   *goohm.MatchResult
		err  error
		root goohm.Node
	)
	if gmr, err = goohm.NewGrammar(ctx, utils.OhmGrammarWasmBytes()); err != nil {
		return "", fmt.Errorf("creating grammar: %v", err)
	}
	defer gmr.Close()
	if mr, err = gmr.Match(vc.GenCmd.Grammar); err != nil {
		return "", fmt.Errorf("matching: %v", err)
	}
	defer mr.Close()
	if !mr.Succeeded() {
		return "", fmt.Errorf("match failed")
	}
	if root, err = mr.GetCstRoot(); err != nil {
		return "", fmt.Errorf("Error getting cst root. %v", err)
	}
	gAst, err := NewBuildGrammars(root).BuildRuleAst(root)
	if err != nil {
		return "", fmt.Errorf("Error building rule ast. %v", err)
	}
	gAst.GenGoInterfaces(vc)
	return vc.GenCmd.sbldr.String(), nil
}

func (gmrs GrammarsNode) GenGoInterfaces(vc *genInterfaceCmd) {
	if vc.GenCmd.GoTypePackage == "" {
		vc.GenCmd.GoTypePackage = strings.ToLower(gmrs.Gmr_names[0])
	}
	vc.GenCmd.outf(`// Code generated by ohmgo generate interfaces - DO NOT EDIT.
package %[1]s

`, vc.GenCmd.GoTypePackage, vc.GenCmd.GoRuntimeImport)
	for _, gname := range gmrs.Gmr_names {
		vc.GenCmd.outf(`// interfaces for grammar %[1]s

`, gname)
		gmr := gmrs.Grammars[gname]
		gmr.GenGoInterfaces(vc)
	}
}

func (gmr GrammarNode) GenGoInterfaces(vc *genInterfaceCmd) {
	for _, rname := range gmr.Rule_names {
		rule := gmr.Rules[rname]
		branch := rule.GetBranch()
		vc.GenCmd.outf(`// %[1]s%[2]s
// -- rule --
`,
			branch.RuleName(),
			branch.Descr(" - ", ""),
		)
		for _, line := range branch.Source() {
			vc.GenCmd.outf(`// %s
`,
				strings.TrimSpace(line),
			)
		}
		type_prefix := "Visitor"
		method_prefix := "Visit"
		if _, is_case := rule.Cast_case_rule(); is_case {
			type_prefix = "Switcher"
			method_prefix = "Switch"
		}
		vc.GenCmd.outf(`// ----
type %[2]s_%[1]s[P, R any] interface {
	%[3]s%[1]s(node *%[1]s[P, R])
}
type %[2]sE_%[1]s[P, R any] interface {
	%[3]s%[1]s(node *%[1]s[P, R]) error
}
type %[2]sP_%[1]s[P, R any] interface {
	%[3]s%[1]s(node *%[1]s[P, R], payload P)
}
type %[2]sPE_%[1]s[P, R any] interface {
	%[3]s%[1]s(node *%[1]s[P, R], payload P) error
}
type %[2]sR_%[1]s[P, R any] interface {
	%[3]s%[1]s(node *%[1]s[P, R]) (result R)
}
type %[2]sRE_%[1]s[P, R any] interface {
	%[3]s%[1]s(node *%[1]s[P, R]) (result R, err error)
}
type %[2]sPR_%[1]s[P, R any] interface {
	%[3]s%[1]s(node *%[1]s[P, R], payload P) (result R)
}
type %[2]sPRE_%[1]s[P, R any] interface {
	%[3]s%[1]s(node *%[1]s[P, R], payload P) (result R, err error)
}

`,
			branch.TypeName(),
			type_prefix,
			method_prefix,
		)
	}
}
