package ruleast

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/ohmjs/goohm"
	"github.com/ohmjs/ohmgo/utils"
	"github.com/samber/lo"
)

type genTypesCmd struct {
	GenCmd     genCmd `opts:"mode=embedded"`
	NoGenerics bool   `opts:"short=g" help:"Do not generate generic types (ie with [P any, R any])"`
	OutputFile string
}

func NewGenTypesCmd() *genTypesCmd {
	return &genTypesCmd{
		GenCmd: genCmd{
			GoRuntimeImport:  "github.com/ohmjs/goohm",
			GoRuntimePackage: "goohm",
			sbldr:            &strings.Builder{},
			// SuffixOutfLineNos: true,
		},
		OutputFile: "-",
	}
}

func (vc *genTypesCmd) Run() error {
	if vc.GenCmd.Grammar[:1] == "@" {
		barr, err := os.ReadFile(vc.GenCmd.Grammar[1:])
		if err != nil {
			return fmt.Errorf("Error reading grammar file. %v", err)
		}
		vc.GenCmd.Grammar = string(barr)
	}
	out, err := vc.Process()
	if err != nil {
		return err
	}
	if vc.OutputFile == "-" {
		fmt.Printf("%[1]s\n", out)
		return nil
	}
	fi, err := os.Create(vc.OutputFile)
	if err != nil {
		return fmt.Errorf("error creating file %w", err)
	}
	defer fi.Close()
	_, err = fi.WriteString(out)
	if err != nil {
		return fmt.Errorf("error writing file %w", err)
	}
	return nil
}

func (vc *genTypesCmd) Process() (string, error) {
	ctx := context.Background()
	var (
		gmr  *goohm.Grammar
		mr   *goohm.MatchResult
		err  error
		root goohm.Node
	)
	if gmr, err = goohm.NewGrammar(ctx, utils.OhmGrammarWasmBytes()); err != nil {
		return "", fmt.Errorf("creating grammar: %v", err)
	}
	defer gmr.Close()
	if mr, err = gmr.Match(vc.GenCmd.Grammar); err != nil {
		return "", fmt.Errorf("matching: %v", err)
	}
	defer mr.Close()
	if !mr.Succeeded() {
		return "", fmt.Errorf("match failed")
	}
	if root, err = mr.GetCstRoot(); err != nil {
		return "", fmt.Errorf("Error getting cst root. %v", err)
	}
	gAst, err := NewBuildGrammars(root).BuildRuleAst(root)
	if err != nil {
		return "", fmt.Errorf("Error building rule ast. %v", err)
	}
	gAst.GenGoTypes(vc)
	return vc.GenCmd.sbldr.String(), nil
}

func (gmrs GrammarsNode) GenGoTypes(vc *genTypesCmd) {
	if vc.GenCmd.GoTypePackage == "" {
		vc.GenCmd.GoTypePackage = strings.ToLower(gmrs.Gmr_names[0])
	}
	vc.GenCmd.outf(`// Code generated by ohmgo generate types - DO NOT EDIT.
package %[1]s

import (
	"%[2]s"
)

`, vc.GenCmd.GoTypePackage, vc.GenCmd.GoRuntimeImport)
	for _, gname := range gmrs.Gmr_names {
		vc.GenCmd.outf(`// types for grammar %[1]s

`, gname)
		gmr := gmrs.Grammars[gname]
		gmr.GenGoTypes(vc)
	}
}

func (gmr GrammarNode) GenGoTypes(vc *genTypesCmd) {
	for _, rname := range gmr.Rule_names {
		rule := gmr.Rules[rname]
		branch := rule.GetBranch()
		vc.GenCmd.outf(`// %[1]s%[2]s
// -- rule --
`,
			branch.RuleName(),
			branch.Descr(" - ", ""),
		)
		for _, line := range branch.Source() {
			vc.GenCmd.outf(`// %[1]s
`,
				strings.TrimSpace(line),
			)
		}
		generics := "[P, R any]"
		if vc.NoGenerics {
			generics = ""
		}
		vc.GenCmd.outf(`// ----
type %[1]s%[2]s struct {
`,
			branch.TypeName(),
			generics,
		)
		branch.GenGoTypes(vc)
		vc.GenCmd.outf(`}

`)
	}
}

func (node VirtRuleNode) GenGoTypes(vc *genTypesCmd) {
	node.Node.GenGoTypes(vc)
}

func (node BareRuleNode) GenGoTypes(vc *genTypesCmd) {
	longest := lo.MaxBy(node.Args, func(a, b NamedArgNode) bool {
		return len(a.Name) > len(b.Name)
	})
	for _, arg := range node.Args {
		padding := strings.Repeat(" ", len(longest.Name)-len(arg.Name))
		vc.GenCmd.outf(`	%[1]s %[2]s%[3]s
`,
			upper1st(arg.Name),
			padding,
			arg.Node.GetBranch().GoType(vc.GenCmd.GoRuntimePackage),
		)
	}
}

func (node CasesRuleNode) GenGoTypes(vc *genTypesCmd) {
	vc.GenCmd.outf(`	%[1]s %[2]s
`,
		"Node",
		vc.GenCmd.GoRuntimePackage+".Node",
	)
}
