// Code generated by goadlc v3 - DO NOT EDIT.
package ruleast

import (
	"fmt"
)

type ArgNode struct {
	Branch ArgNodeBranch
}

type ArgNodeBranch interface {
	isArgNodeBranch()
}

func (*ArgNode) MakeNewBranch(key string) (any, error) {
	switch key {
	case "node":
		return &_ArgNode_Node{}, nil
	case "rule":
		return &_ArgNode_Rule{}, nil
	case "term":
		return &_ArgNode_Term{}, nil
	case "list":
		return &_ArgNode_List{}, nil
	case "opt":
		return &_ArgNode_Opt{}, nil
	case "bhor":
		return &_ArgNode_Bhor{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _ArgNode_Node struct {
	V NodeArgNode `branch:"node"`
}
type _ArgNode_Rule struct {
	V RuleArgNode `branch:"rule"`
}
type _ArgNode_Term struct {
	V TermArgNode `branch:"term"`
}
type _ArgNode_List struct {
	V ListArgNode `branch:"list"`
}
type _ArgNode_Opt struct {
	V OptArgNode `branch:"opt"`
}
type _ArgNode_Bhor struct {
	V BuiltinHorArgNode `branch:"bhor"`
}

func (_ArgNode_Node) isArgNodeBranch() {}
func (_ArgNode_Rule) isArgNodeBranch() {}
func (_ArgNode_Term) isArgNodeBranch() {}
func (_ArgNode_List) isArgNodeBranch() {}
func (_ArgNode_Opt) isArgNodeBranch()  {}
func (_ArgNode_Bhor) isArgNodeBranch() {}

func Make_ArgNode_node(v NodeArgNode) ArgNode {
	return ArgNode{
		_ArgNode_Node{v},
	}
}

func Make_ArgNode_rule(v RuleArgNode) ArgNode {
	return ArgNode{
		_ArgNode_Rule{v},
	}
}

func Make_ArgNode_term(v TermArgNode) ArgNode {
	return ArgNode{
		_ArgNode_Term{v},
	}
}

func Make_ArgNode_list(v ListArgNode) ArgNode {
	return ArgNode{
		_ArgNode_List{v},
	}
}

func Make_ArgNode_opt(v OptArgNode) ArgNode {
	return ArgNode{
		_ArgNode_Opt{v},
	}
}

func Make_ArgNode_bhor(v BuiltinHorArgNode) ArgNode {
	return ArgNode{
		_ArgNode_Bhor{v},
	}
}

func (un ArgNode) Cast_node() (NodeArgNode, bool) {
	br, ok := un.Branch.(_ArgNode_Node)
	return br.V, ok
}

func (un ArgNode) Cast_rule() (RuleArgNode, bool) {
	br, ok := un.Branch.(_ArgNode_Rule)
	return br.V, ok
}

func (un ArgNode) Cast_term() (TermArgNode, bool) {
	br, ok := un.Branch.(_ArgNode_Term)
	return br.V, ok
}

func (un ArgNode) Cast_list() (ListArgNode, bool) {
	br, ok := un.Branch.(_ArgNode_List)
	return br.V, ok
}

func (un ArgNode) Cast_opt() (OptArgNode, bool) {
	br, ok := un.Branch.(_ArgNode_Opt)
	return br.V, ok
}

func (un ArgNode) Cast_bhor() (BuiltinHorArgNode, bool) {
	br, ok := un.Branch.(_ArgNode_Bhor)
	return br.V, ok
}

func Handle_ArgNode[T any](
	_in ArgNode,
	node func(node NodeArgNode) T,
	rule func(rule RuleArgNode) T,
	term func(term TermArgNode) T,
	list func(list ListArgNode) T,
	opt func(opt OptArgNode) T,
	bhor func(bhor BuiltinHorArgNode) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _ArgNode_Node:
		if node != nil {
			return node(_b.V)
		}
	case _ArgNode_Rule:
		if rule != nil {
			return rule(_b.V)
		}
	case _ArgNode_Term:
		if term != nil {
			return term(_b.V)
		}
	case _ArgNode_List:
		if list != nil {
			return list(_b.V)
		}
	case _ArgNode_Opt:
		if opt != nil {
			return opt(_b.V)
		}
	case _ArgNode_Bhor:
		if bhor != nil {
			return bhor(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : ArgNode")
}

func HandleWithErr_ArgNode[T any](
	_in ArgNode,
	node func(node NodeArgNode) (T, error),
	rule func(rule RuleArgNode) (T, error),
	term func(term TermArgNode) (T, error),
	list func(list ListArgNode) (T, error),
	opt func(opt OptArgNode) (T, error),
	bhor func(bhor BuiltinHorArgNode) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _ArgNode_Node:
		if node != nil {
			return node(_b.V)
		}
	case _ArgNode_Rule:
		if rule != nil {
			return rule(_b.V)
		}
	case _ArgNode_Term:
		if term != nil {
			return term(_b.V)
		}
	case _ArgNode_List:
		if list != nil {
			return list(_b.V)
		}
	case _ArgNode_Opt:
		if opt != nil {
			return opt(_b.V)
		}
	case _ArgNode_Bhor:
		if bhor != nil {
			return bhor(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : ArgNode")
}

type BareNode struct {
	_BareNode
}

type _BareNode struct {
	Args []NamedArgNode `json:"args"`
}

func MakeAll_BareNode(
	args []NamedArgNode,
) BareNode {
	return BareNode{
		_BareNode{
			Args: args,
		},
	}
}

func Make_BareNode(
	args []NamedArgNode,
) BareNode {
	ret := BareNode{
		_BareNode{
			Args: args,
		},
	}
	return ret
}

type BareRuleNode struct {
	_BareRuleNode
}

type _BareRuleNode struct {
	Name   string         `json:"name"`
	Rtype  RuleType       `json:"rtype"`
	Descr  string         `json:"descr"`
	Source string         `json:"source"`
	Args   []NamedArgNode `json:"args"`
}

func MakeAll_BareRuleNode(
	name string,
	rtype RuleType,
	descr string,
	source string,
	args []NamedArgNode,
) BareRuleNode {
	return BareRuleNode{
		_BareRuleNode{
			Name:   name,
			Rtype:  rtype,
			Descr:  descr,
			Source: source,
			Args:   args,
		},
	}
}

func Make_BareRuleNode(
	name string,
	rtype RuleType,
	descr string,
	source string,
	args []NamedArgNode,
) BareRuleNode {
	ret := BareRuleNode{
		_BareRuleNode{
			Name:   name,
			Rtype:  rtype,
			Descr:  descr,
			Source: source,
			Args:   args,
		},
	}
	return ret
}

type BuiltinHorArgNode struct {
	_BuiltinHorArgNode
}

type _BuiltinHorArgNode struct {
	List_type string       `json:"list_type"`
	Elem      NamedArgNode `json:"elem"`
	Sep       NamedArgNode `json:"sep"`
}

func MakeAll_BuiltinHorArgNode(
	list_type string,
	elem NamedArgNode,
	sep NamedArgNode,
) BuiltinHorArgNode {
	return BuiltinHorArgNode{
		_BuiltinHorArgNode{
			List_type: list_type,
			Elem:      elem,
			Sep:       sep,
		},
	}
}

func Make_BuiltinHorArgNode(
	list_type string,
	elem NamedArgNode,
	sep NamedArgNode,
) BuiltinHorArgNode {
	ret := BuiltinHorArgNode{
		_BuiltinHorArgNode{
			List_type: list_type,
			Elem:      elem,
			Sep:       sep,
		},
	}
	return ret
}

type CasesRuleNode struct {
	_CasesRuleNode
}

type _CasesRuleNode struct {
	Name   string         `json:"name"`
	Rtype  RuleType       `json:"rtype"`
	Descr  string         `json:"descr"`
	Source string         `json:"source"`
	Args   []NamedArgNode `json:"args"`
	Cases  []InlineNode   `json:"cases"`
}

func MakeAll_CasesRuleNode(
	name string,
	rtype RuleType,
	descr string,
	source string,
	args []NamedArgNode,
	cases []InlineNode,
) CasesRuleNode {
	return CasesRuleNode{
		_CasesRuleNode{
			Name:   name,
			Rtype:  rtype,
			Descr:  descr,
			Source: source,
			Args:   args,
			Cases:  cases,
		},
	}
}

func Make_CasesRuleNode(
	name string,
	rtype RuleType,
	descr string,
	source string,
	args []NamedArgNode,
	cases []InlineNode,
) CasesRuleNode {
	ret := CasesRuleNode{
		_CasesRuleNode{
			Name:   name,
			Rtype:  rtype,
			Descr:  descr,
			Source: source,
			Args:   args,
			Cases:  cases,
		},
	}
	return ret
}

type GrammarNode struct {
	_GrammarNode
}

type _GrammarNode struct {
	Name       string              `json:"name"`
	Rule_names []string            `json:"rule_names"`
	Rules      map[string]RuleNode `json:"rules"`
}

func MakeAll_GrammarNode(
	name string,
	rule_names []string,
	rules map[string]RuleNode,
) GrammarNode {
	return GrammarNode{
		_GrammarNode{
			Name:       name,
			Rule_names: rule_names,
			Rules:      rules,
		},
	}
}

func Make_GrammarNode(
	name string,
	rule_names []string,
	rules map[string]RuleNode,
) GrammarNode {
	ret := GrammarNode{
		_GrammarNode{
			Name:       name,
			Rule_names: rule_names,
			Rules:      rules,
		},
	}
	return ret
}

type GrammarsNode struct {
	_GrammarsNode
}

type _GrammarsNode struct {
	Gmr_names []string               `json:"gmr_names"`
	Grammars  map[string]GrammarNode `json:"grammars"`
}

func MakeAll_GrammarsNode(
	gmr_names []string,
	grammars map[string]GrammarNode,
) GrammarsNode {
	return GrammarsNode{
		_GrammarsNode{
			Gmr_names: gmr_names,
			Grammars:  grammars,
		},
	}
}

func Make_GrammarsNode(
	gmr_names []string,
	grammars map[string]GrammarNode,
) GrammarsNode {
	ret := GrammarsNode{
		_GrammarsNode{
			Gmr_names: gmr_names,
			Grammars:  grammars,
		},
	}
	return ret
}

type InlineNode struct {
	_InlineNode
}

type _InlineNode struct {
	Case_name string         `json:"case_name"`
	Source    string         `json:"source"`
	Args      []NamedArgNode `json:"args"`
}

func MakeAll_InlineNode(
	case_name string,
	source string,
	args []NamedArgNode,
) InlineNode {
	return InlineNode{
		_InlineNode{
			Case_name: case_name,
			Source:    source,
			Args:      args,
		},
	}
}

func Make_InlineNode(
	case_name string,
	source string,
	args []NamedArgNode,
) InlineNode {
	ret := InlineNode{
		_InlineNode{
			Case_name: case_name,
			Source:    source,
			Args:      args,
		},
	}
	return ret
}

type ListArgNode struct {
	_ListArgNode
}

type _ListArgNode struct {
	Elem ArgNode `json:"elem"`
}

func MakeAll_ListArgNode(
	elem ArgNode,
) ListArgNode {
	return ListArgNode{
		_ListArgNode{
			Elem: elem,
		},
	}
}

func Make_ListArgNode(
	elem ArgNode,
) ListArgNode {
	ret := ListArgNode{
		_ListArgNode{
			Elem: elem,
		},
	}
	return ret
}

type Named[N any] struct {
	_Named[N]
}

type _Named[N any] struct {
	Name string `json:"name"`
	Node N      `json:"node"`
}

func MakeAll_Named[N any](
	name string,
	node N,
) Named[N] {
	return Named[N]{
		_Named[N]{
			Name: name,
			Node: node,
		},
	}
}

func Make_Named[N any](
	name string,
	node N,
) Named[N] {
	ret := Named[N]{
		_Named[N]{
			Name: name,
			Node: node,
		},
	}
	return ret
}

type NamedArgNode Named[ArgNode]

type NodeArgNode struct {
	_NodeArgNode
}

type _NodeArgNode struct {
}

func MakeAll_NodeArgNode() NodeArgNode {
	return NodeArgNode{
		_NodeArgNode{},
	}
}

func Make_NodeArgNode() NodeArgNode {
	ret := NodeArgNode{
		_NodeArgNode{},
	}
	return ret
}

type OptArgNode struct {
	_OptArgNode
}

type _OptArgNode struct {
	Elem ArgNode `json:"elem"`
}

func MakeAll_OptArgNode(
	elem ArgNode,
) OptArgNode {
	return OptArgNode{
		_OptArgNode{
			Elem: elem,
		},
	}
}

func Make_OptArgNode(
	elem ArgNode,
) OptArgNode {
	ret := OptArgNode{
		_OptArgNode{
			Elem: elem,
		},
	}
	return ret
}

type RuleArgNode struct {
	_RuleArgNode
}

type _RuleArgNode struct {
	Rule string `json:"rule"`
}

func MakeAll_RuleArgNode(
	rule string,
) RuleArgNode {
	return RuleArgNode{
		_RuleArgNode{
			Rule: rule,
		},
	}
}

func Make_RuleArgNode(
	rule string,
) RuleArgNode {
	ret := RuleArgNode{
		_RuleArgNode{
			Rule: rule,
		},
	}
	return ret
}

type RuleDetailNode struct {
	Branch RuleDetailNodeBranch
}

type RuleDetailNodeBranch interface {
	isRuleDetailNodeBranch()
}

func (*RuleDetailNode) MakeNewBranch(key string) (any, error) {
	switch key {
	case "inline":
		return &_RuleDetailNode_Inline{}, nil
	case "bare":
		return &_RuleDetailNode_Bare{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _RuleDetailNode_Inline struct {
	V InlineNode `branch:"inline"`
}
type _RuleDetailNode_Bare struct {
	V BareNode `branch:"bare"`
}

func (_RuleDetailNode_Inline) isRuleDetailNodeBranch() {}
func (_RuleDetailNode_Bare) isRuleDetailNodeBranch()   {}

func Make_RuleDetailNode_inline(v InlineNode) RuleDetailNode {
	return RuleDetailNode{
		_RuleDetailNode_Inline{v},
	}
}

func Make_RuleDetailNode_bare(v BareNode) RuleDetailNode {
	return RuleDetailNode{
		_RuleDetailNode_Bare{v},
	}
}

func (un RuleDetailNode) Cast_inline() (InlineNode, bool) {
	br, ok := un.Branch.(_RuleDetailNode_Inline)
	return br.V, ok
}

func (un RuleDetailNode) Cast_bare() (BareNode, bool) {
	br, ok := un.Branch.(_RuleDetailNode_Bare)
	return br.V, ok
}

func Handle_RuleDetailNode[T any](
	_in RuleDetailNode,
	inline func(inline InlineNode) T,
	bare func(bare BareNode) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _RuleDetailNode_Inline:
		if inline != nil {
			return inline(_b.V)
		}
	case _RuleDetailNode_Bare:
		if bare != nil {
			return bare(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleDetailNode")
}

func HandleWithErr_RuleDetailNode[T any](
	_in RuleDetailNode,
	inline func(inline InlineNode) (T, error),
	bare func(bare BareNode) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _RuleDetailNode_Inline:
		if inline != nil {
			return inline(_b.V)
		}
	case _RuleDetailNode_Bare:
		if bare != nil {
			return bare(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleDetailNode")
}

type RuleNode struct {
	Branch RuleNodeBranch
}

type RuleNodeBranch interface {
	isRuleNodeBranch()
}

func (*RuleNode) MakeNewBranch(key string) (any, error) {
	switch key {
	case "bare_rule":
		return &_RuleNode_Bare_rule{}, nil
	case "virt_rule":
		return &_RuleNode_Virt_rule{}, nil
	case "case_rule":
		return &_RuleNode_Case_rule{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _RuleNode_Bare_rule struct {
	V BareRuleNode `branch:"bare_rule"`
}
type _RuleNode_Virt_rule struct {
	V VirtRuleNode `branch:"virt_rule"`
}
type _RuleNode_Case_rule struct {
	V CasesRuleNode `branch:"case_rule"`
}

func (_RuleNode_Bare_rule) isRuleNodeBranch() {}
func (_RuleNode_Virt_rule) isRuleNodeBranch() {}
func (_RuleNode_Case_rule) isRuleNodeBranch() {}

func Make_RuleNode_bare_rule(v BareRuleNode) RuleNode {
	return RuleNode{
		_RuleNode_Bare_rule{v},
	}
}

func Make_RuleNode_virt_rule(v VirtRuleNode) RuleNode {
	return RuleNode{
		_RuleNode_Virt_rule{v},
	}
}

func Make_RuleNode_case_rule(v CasesRuleNode) RuleNode {
	return RuleNode{
		_RuleNode_Case_rule{v},
	}
}

func (un RuleNode) Cast_bare_rule() (BareRuleNode, bool) {
	br, ok := un.Branch.(_RuleNode_Bare_rule)
	return br.V, ok
}

func (un RuleNode) Cast_virt_rule() (VirtRuleNode, bool) {
	br, ok := un.Branch.(_RuleNode_Virt_rule)
	return br.V, ok
}

func (un RuleNode) Cast_case_rule() (CasesRuleNode, bool) {
	br, ok := un.Branch.(_RuleNode_Case_rule)
	return br.V, ok
}

func Handle_RuleNode[T any](
	_in RuleNode,
	bare_rule func(bare_rule BareRuleNode) T,
	virt_rule func(virt_rule VirtRuleNode) T,
	case_rule func(case_rule CasesRuleNode) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _RuleNode_Bare_rule:
		if bare_rule != nil {
			return bare_rule(_b.V)
		}
	case _RuleNode_Virt_rule:
		if virt_rule != nil {
			return virt_rule(_b.V)
		}
	case _RuleNode_Case_rule:
		if case_rule != nil {
			return case_rule(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleNode")
}

func HandleWithErr_RuleNode[T any](
	_in RuleNode,
	bare_rule func(bare_rule BareRuleNode) (T, error),
	virt_rule func(virt_rule VirtRuleNode) (T, error),
	case_rule func(case_rule CasesRuleNode) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _RuleNode_Bare_rule:
		if bare_rule != nil {
			return bare_rule(_b.V)
		}
	case _RuleNode_Virt_rule:
		if virt_rule != nil {
			return virt_rule(_b.V)
		}
	case _RuleNode_Case_rule:
		if case_rule != nil {
			return case_rule(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleNode")
}

type RuleType struct {
	Branch RuleTypeBranch
}

type RuleTypeBranch interface {
	isRuleTypeBranch()
}

func (*RuleType) MakeNewBranch(key string) (any, error) {
	switch key {
	case "define":
		return &_RuleType_Define{}, nil
	case "override":
		return &_RuleType_Override{}, nil
	case "extend":
		return &_RuleType_Extend{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _RuleType_Define struct {
	V struct{} `branch:"define"`
}
type _RuleType_Override struct {
	V struct{} `branch:"override"`
}
type _RuleType_Extend struct {
	V struct{} `branch:"extend"`
}

func (_RuleType_Define) isRuleTypeBranch()   {}
func (_RuleType_Override) isRuleTypeBranch() {}
func (_RuleType_Extend) isRuleTypeBranch()   {}

func Make_RuleType_define() RuleType {
	return RuleType{
		_RuleType_Define{struct{}{}},
	}
}

func Make_RuleType_override() RuleType {
	return RuleType{
		_RuleType_Override{struct{}{}},
	}
}

func Make_RuleType_extend() RuleType {
	return RuleType{
		_RuleType_Extend{struct{}{}},
	}
}

func (un RuleType) Cast_define() (struct{}, bool) {
	br, ok := un.Branch.(_RuleType_Define)
	return br.V, ok
}

func (un RuleType) Cast_override() (struct{}, bool) {
	br, ok := un.Branch.(_RuleType_Override)
	return br.V, ok
}

func (un RuleType) Cast_extend() (struct{}, bool) {
	br, ok := un.Branch.(_RuleType_Extend)
	return br.V, ok
}

func Handle_RuleType[T any](
	_in RuleType,
	define func(define struct{}) T,
	override func(override struct{}) T,
	extend func(extend struct{}) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _RuleType_Define:
		if define != nil {
			return define(_b.V)
		}
	case _RuleType_Override:
		if override != nil {
			return override(_b.V)
		}
	case _RuleType_Extend:
		if extend != nil {
			return extend(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleType")
}

func HandleWithErr_RuleType[T any](
	_in RuleType,
	define func(define struct{}) (T, error),
	override func(override struct{}) (T, error),
	extend func(extend struct{}) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _RuleType_Define:
		if define != nil {
			return define(_b.V)
		}
	case _RuleType_Override:
		if override != nil {
			return override(_b.V)
		}
	case _RuleType_Extend:
		if extend != nil {
			return extend(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleType")
}

type TermArgNode struct {
	_TermArgNode
}

type _TermArgNode struct {
}

func MakeAll_TermArgNode() TermArgNode {
	return TermArgNode{
		_TermArgNode{},
	}
}

func Make_TermArgNode() TermArgNode {
	ret := TermArgNode{
		_TermArgNode{},
	}
	return ret
}

type VirtRuleNode Named[BareRuleNode]
