// Code generated by goadlc v3 - DO NOT EDIT.
package ruleast

import (
	goadl "github.com/adl-lang/goadl_rt/v3"
	"github.com/adl-lang/goadl_rt/v3/customtypes"
	"github.com/adl-lang/goadl_rt/v3/sys/adlast"
	"github.com/adl-lang/goadl_rt/v3/sys/types"
)

func Texpr_ArgNode() adlast.ATypeExpr[ArgNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "ArgNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[ArgNode](te)
}

func AST_ArgNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"ArgNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_union_(
			adlast.MakeAll_Union(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"node",
						"node",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"NodeArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"rule",
						"rule",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"RuleArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"term",
						"term",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"TermArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"list",
						"list",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"ListArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"opt",
						"opt",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"OptArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"bhor",
						"bhor",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"BuiltinHorArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "ArgNode"),
		AST_ArgNode(),
	)
}

func Texpr_BareNode() adlast.ATypeExpr[BareNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "BareNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[BareNode](te)
}

func AST_BareNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"BareNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"args",
						"args",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Vector",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_reference(
										adlast.MakeAll_ScopedName(
											"ruleast",
											"NamedArgNode",
										),
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "BareNode"),
		AST_BareNode(),
	)
}

func Texpr_BareRuleNode() adlast.ATypeExpr[BareRuleNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "BareRuleNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[BareRuleNode](te)
}

func AST_BareRuleNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"BareRuleNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"name",
						"name",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"rtype",
						"rtype",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"RuleType",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"descr",
						"descr",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"source",
						"source",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"args",
						"args",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Vector",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_reference(
										adlast.MakeAll_ScopedName(
											"ruleast",
											"NamedArgNode",
										),
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "BareRuleNode"),
		AST_BareRuleNode(),
	)
}

func Texpr_BuiltinHorArgNode() adlast.ATypeExpr[BuiltinHorArgNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "BuiltinHorArgNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[BuiltinHorArgNode](te)
}

func AST_BuiltinHorArgNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"BuiltinHorArgNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"list_type",
						"list_type",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"elem",
						"elem",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"NamedArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"sep",
						"sep",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"NamedArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "BuiltinHorArgNode"),
		AST_BuiltinHorArgNode(),
	)
}

func Texpr_CasesRuleNode() adlast.ATypeExpr[CasesRuleNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "CasesRuleNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[CasesRuleNode](te)
}

func AST_CasesRuleNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"CasesRuleNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"name",
						"name",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"rtype",
						"rtype",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"RuleType",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"descr",
						"descr",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"source",
						"source",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"args",
						"args",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Vector",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_reference(
										adlast.MakeAll_ScopedName(
											"ruleast",
											"NamedArgNode",
										),
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"cases",
						"cases",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Vector",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_reference(
										adlast.MakeAll_ScopedName(
											"ruleast",
											"InlineNode",
										),
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "CasesRuleNode"),
		AST_CasesRuleNode(),
	)
}

func Texpr_GrammarNode() adlast.ATypeExpr[GrammarNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "GrammarNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[GrammarNode](te)
}

func AST_GrammarNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"GrammarNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"name",
						"name",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"rule_names",
						"rule_names",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Vector",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_primitive(
										"String",
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"rules",
						"rules",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"StringMap",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_reference(
										adlast.MakeAll_ScopedName(
											"ruleast",
											"RuleNode",
										),
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "GrammarNode"),
		AST_GrammarNode(),
	)
}

func Texpr_GrammarsNode() adlast.ATypeExpr[GrammarsNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "GrammarsNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[GrammarsNode](te)
}

func AST_GrammarsNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"GrammarsNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"gmr_names",
						"gmr_names",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Vector",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_primitive(
										"String",
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"grammars",
						"grammars",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"StringMap",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_reference(
										adlast.MakeAll_ScopedName(
											"ruleast",
											"GrammarNode",
										),
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "GrammarsNode"),
		AST_GrammarsNode(),
	)
}

func Texpr_InlineNode() adlast.ATypeExpr[InlineNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "InlineNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[InlineNode](te)
}

func AST_InlineNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"InlineNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"case_name",
						"case_name",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"source",
						"source",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"args",
						"args",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Vector",
							),
							[]adlast.TypeExpr{
								adlast.MakeAll_TypeExpr(
									adlast.Make_TypeRef_reference(
										adlast.MakeAll_ScopedName(
											"ruleast",
											"NamedArgNode",
										),
									),
									[]adlast.TypeExpr{},
								),
							},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "InlineNode"),
		AST_InlineNode(),
	)
}

func Texpr_ListArgNode() adlast.ATypeExpr[ListArgNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "ListArgNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[ListArgNode](te)
}

func AST_ListArgNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"ListArgNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"elem",
						"elem",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"ArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "ListArgNode"),
		AST_ListArgNode(),
	)
}

func Texpr_Named[N any](n adlast.ATypeExpr[N]) adlast.ATypeExpr[Named[N]] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "Named"),
		),
		[]adlast.TypeExpr{n.Value},
	)
	return adlast.Make_ATypeExpr[Named[N]](te)
}

func AST_Named() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"Named",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{
					"N",
				},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"name",
						"name",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"node",
						"node",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_typeParam(
								"N",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "Named"),
		AST_Named(),
	)
}

func Texpr_NamedArgNode() adlast.ATypeExpr[NamedArgNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "NamedArgNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[NamedArgNode](te)
}

func AST_NamedArgNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"NamedArgNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_newtype_(
			adlast.MakeAll_NewType(
				[]adlast.Ident{},
				adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"ruleast",
							"Named",
						),
					),
					[]adlast.TypeExpr{
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"ArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
					},
				),
				types.Make_Maybe_nothing[any](),
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "NamedArgNode"),
		AST_NamedArgNode(),
	)
}

func Texpr_NodeArgNode() adlast.ATypeExpr[NodeArgNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "NodeArgNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[NodeArgNode](te)
}

func AST_NodeArgNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"NodeArgNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "NodeArgNode"),
		AST_NodeArgNode(),
	)
}

func Texpr_OptArgNode() adlast.ATypeExpr[OptArgNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "OptArgNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[OptArgNode](te)
}

func AST_OptArgNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"OptArgNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"elem",
						"elem",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"ArgNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "OptArgNode"),
		AST_OptArgNode(),
	)
}

func Texpr_RuleArgNode() adlast.ATypeExpr[RuleArgNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "RuleArgNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[RuleArgNode](te)
}

func AST_RuleArgNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"RuleArgNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"rule",
						"rule",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"String",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "RuleArgNode"),
		AST_RuleArgNode(),
	)
}

func Texpr_RuleDetailNode() adlast.ATypeExpr[RuleDetailNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "RuleDetailNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[RuleDetailNode](te)
}

func AST_RuleDetailNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"RuleDetailNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_union_(
			adlast.MakeAll_Union(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"inline",
						"inline",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"InlineNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"bare",
						"bare",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"BareNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "RuleDetailNode"),
		AST_RuleDetailNode(),
	)
}

func Texpr_RuleNode() adlast.ATypeExpr[RuleNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "RuleNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[RuleNode](te)
}

func AST_RuleNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"RuleNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_union_(
			adlast.MakeAll_Union(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"bare_rule",
						"bare_rule",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"BareRuleNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"virt_rule",
						"virt_rule",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"VirtRuleNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"case_rule",
						"case_rule",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"CasesRuleNode",
								),
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "RuleNode"),
		AST_RuleNode(),
	)
}

func Texpr_RuleType() adlast.ATypeExpr[RuleType] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "RuleType"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[RuleType](te)
}

func AST_RuleType() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"RuleType",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_union_(
			adlast.MakeAll_Union(
				[]adlast.Ident{},
				[]adlast.Field{
					adlast.MakeAll_Field(
						"define",
						"define",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Void",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"override",
						"override",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Void",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
					adlast.MakeAll_Field(
						"extend",
						"extend",
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_primitive(
								"Void",
							),
							[]adlast.TypeExpr{},
						),
						types.Make_Maybe_nothing[any](),
						customtypes.MapMap[adlast.ScopedName, any]{},
					),
				},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "RuleType"),
		AST_RuleType(),
	)
}

func Texpr_TermArgNode() adlast.ATypeExpr[TermArgNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "TermArgNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[TermArgNode](te)
}

func AST_TermArgNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"TermArgNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_struct_(
			adlast.MakeAll_Struct(
				[]adlast.Ident{},
				[]adlast.Field{},
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "TermArgNode"),
		AST_TermArgNode(),
	)
}

func Texpr_VirtRuleNode() adlast.ATypeExpr[VirtRuleNode] {
	te := adlast.Make_TypeExpr(
		adlast.Make_TypeRef_reference(
			adlast.Make_ScopedName("ruleast", "VirtRuleNode"),
		),
		[]adlast.TypeExpr{},
	)
	return adlast.Make_ATypeExpr[VirtRuleNode](te)
}

func AST_VirtRuleNode() adlast.ScopedDecl {
	decl := adlast.MakeAll_Decl(
		"VirtRuleNode",
		types.Make_Maybe_nothing[uint32](),
		adlast.Make_DeclType_newtype_(
			adlast.MakeAll_NewType(
				[]adlast.Ident{},
				adlast.MakeAll_TypeExpr(
					adlast.Make_TypeRef_reference(
						adlast.MakeAll_ScopedName(
							"ruleast",
							"Named",
						),
					),
					[]adlast.TypeExpr{
						adlast.MakeAll_TypeExpr(
							adlast.Make_TypeRef_reference(
								adlast.MakeAll_ScopedName(
									"ruleast",
									"BareRuleNode",
								),
							),
							[]adlast.TypeExpr{},
						),
					},
				),
				types.Make_Maybe_nothing[any](),
			),
		),
		customtypes.MapMap[adlast.ScopedName, any]{},
	)
	return adlast.Make_ScopedDecl("ruleast", decl)
}

func init() {
	goadl.RESOLVER.Register(
		adlast.Make_ScopedName("ruleast", "VirtRuleNode"),
		AST_VirtRuleNode(),
	)
}
