// Code generated by goadlc v3 - DO NOT EDIT.
package ruleast

import (
	"fmt"
)

type ArgNode struct {
	Branch ArgNodeBranch
}

type ArgNodeBranch interface {
	isArgNodeBranch()
}

func (*ArgNode) MakeNewBranch(key string) (any, error) {
	switch key {
	case "nobj":
		return &_ArgNode_Nobj{}, nil
	case "rule":
		return &_ArgNode_Rule{}, nil
	case "term":
		return &_ArgNode_Term{}, nil
	case "list":
		return &_ArgNode_List{}, nil
	case "opt":
		return &_ArgNode_Opt{}, nil
	case "bhor":
		return &_ArgNode_Bhor{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _ArgNode_Nobj struct {
	V NObjNode `branch:"nobj"`
}
type _ArgNode_Rule struct {
	V NontNode `branch:"rule"`
}
type _ArgNode_Term struct {
	V TermNode `branch:"term"`
}
type _ArgNode_List struct {
	V ListNode `branch:"list"`
}
type _ArgNode_Opt struct {
	V OptNode `branch:"opt"`
}
type _ArgNode_Bhor struct {
	V BuiltinHOR `branch:"bhor"`
}

func (_ArgNode_Nobj) isArgNodeBranch() {}
func (_ArgNode_Rule) isArgNodeBranch() {}
func (_ArgNode_Term) isArgNodeBranch() {}
func (_ArgNode_List) isArgNodeBranch() {}
func (_ArgNode_Opt) isArgNodeBranch()  {}
func (_ArgNode_Bhor) isArgNodeBranch() {}

func Make_ArgNode_nobj(v NObjNode) ArgNode {
	return ArgNode{
		_ArgNode_Nobj{v},
	}
}

func Make_ArgNode_rule(v NontNode) ArgNode {
	return ArgNode{
		_ArgNode_Rule{v},
	}
}

func Make_ArgNode_term(v TermNode) ArgNode {
	return ArgNode{
		_ArgNode_Term{v},
	}
}

func Make_ArgNode_list(v ListNode) ArgNode {
	return ArgNode{
		_ArgNode_List{v},
	}
}

func Make_ArgNode_opt(v OptNode) ArgNode {
	return ArgNode{
		_ArgNode_Opt{v},
	}
}

func Make_ArgNode_bhor(v BuiltinHOR) ArgNode {
	return ArgNode{
		_ArgNode_Bhor{v},
	}
}

func (un ArgNode) Cast_nobj() (NObjNode, bool) {
	br, ok := un.Branch.(_ArgNode_Nobj)
	return br.V, ok
}

func (un ArgNode) Cast_rule() (NontNode, bool) {
	br, ok := un.Branch.(_ArgNode_Rule)
	return br.V, ok
}

func (un ArgNode) Cast_term() (TermNode, bool) {
	br, ok := un.Branch.(_ArgNode_Term)
	return br.V, ok
}

func (un ArgNode) Cast_list() (ListNode, bool) {
	br, ok := un.Branch.(_ArgNode_List)
	return br.V, ok
}

func (un ArgNode) Cast_opt() (OptNode, bool) {
	br, ok := un.Branch.(_ArgNode_Opt)
	return br.V, ok
}

func (un ArgNode) Cast_bhor() (BuiltinHOR, bool) {
	br, ok := un.Branch.(_ArgNode_Bhor)
	return br.V, ok
}

func Handle_ArgNode[T any](
	_in ArgNode,
	nobj func(nobj NObjNode) T,
	rule func(rule NontNode) T,
	term func(term TermNode) T,
	list func(list ListNode) T,
	opt func(opt OptNode) T,
	bhor func(bhor BuiltinHOR) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _ArgNode_Nobj:
		if nobj != nil {
			return nobj(_b.V)
		}
	case _ArgNode_Rule:
		if rule != nil {
			return rule(_b.V)
		}
	case _ArgNode_Term:
		if term != nil {
			return term(_b.V)
		}
	case _ArgNode_List:
		if list != nil {
			return list(_b.V)
		}
	case _ArgNode_Opt:
		if opt != nil {
			return opt(_b.V)
		}
	case _ArgNode_Bhor:
		if bhor != nil {
			return bhor(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : ArgNode")
}

func HandleWithErr_ArgNode[T any](
	_in ArgNode,
	nobj func(nobj NObjNode) (T, error),
	rule func(rule NontNode) (T, error),
	term func(term TermNode) (T, error),
	list func(list ListNode) (T, error),
	opt func(opt OptNode) (T, error),
	bhor func(bhor BuiltinHOR) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _ArgNode_Nobj:
		if nobj != nil {
			return nobj(_b.V)
		}
	case _ArgNode_Rule:
		if rule != nil {
			return rule(_b.V)
		}
	case _ArgNode_Term:
		if term != nil {
			return term(_b.V)
		}
	case _ArgNode_List:
		if list != nil {
			return list(_b.V)
		}
	case _ArgNode_Opt:
		if opt != nil {
			return opt(_b.V)
		}
	case _ArgNode_Bhor:
		if bhor != nil {
			return bhor(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : ArgNode")
}

type BareNode struct {
	_BareNode
}

type _BareNode struct {
	Args []NamedArgNode `json:"args"`
}

func MakeAll_BareNode(
	args []NamedArgNode,
) BareNode {
	return BareNode{
		_BareNode{
			Args: args,
		},
	}
}

func Make_BareNode(
	args []NamedArgNode,
) BareNode {
	ret := BareNode{
		_BareNode{
			Args: args,
		},
	}
	return ret
}

type BareRuleNode struct {
	_BareRuleNode
}

type _BareRuleNode struct {
	Name   string         `json:"name"`
	Rtype  RuleType       `json:"rtype"`
	Descr  string         `json:"descr"`
	Source string         `json:"source"`
	Args   []NamedArgNode `json:"args"`
}

func MakeAll_BareRuleNode(
	name string,
	rtype RuleType,
	descr string,
	source string,
	args []NamedArgNode,
) BareRuleNode {
	return BareRuleNode{
		_BareRuleNode{
			Name:   name,
			Rtype:  rtype,
			Descr:  descr,
			Source: source,
			Args:   args,
		},
	}
}

func Make_BareRuleNode(
	name string,
	rtype RuleType,
	descr string,
	source string,
	args []NamedArgNode,
) BareRuleNode {
	ret := BareRuleNode{
		_BareRuleNode{
			Name:   name,
			Rtype:  rtype,
			Descr:  descr,
			Source: source,
			Args:   args,
		},
	}
	return ret
}

type BuiltinHOR struct {
	_BuiltinHOR
}

type _BuiltinHOR struct {
	List_type string       `json:"list_type"`
	Elem      NamedArgNode `json:"elem"`
	Sep       NamedArgNode `json:"sep"`
}

func MakeAll_BuiltinHOR(
	list_type string,
	elem NamedArgNode,
	sep NamedArgNode,
) BuiltinHOR {
	return BuiltinHOR{
		_BuiltinHOR{
			List_type: list_type,
			Elem:      elem,
			Sep:       sep,
		},
	}
}

func Make_BuiltinHOR(
	list_type string,
	elem NamedArgNode,
	sep NamedArgNode,
) BuiltinHOR {
	ret := BuiltinHOR{
		_BuiltinHOR{
			List_type: list_type,
			Elem:      elem,
			Sep:       sep,
		},
	}
	return ret
}

type CasesRuleNode struct {
	_CasesRuleNode
}

type _CasesRuleNode struct {
	Name   string         `json:"name"`
	Rtype  RuleType       `json:"rtype"`
	Descr  string         `json:"descr"`
	Source string         `json:"source"`
	Args   []NamedArgNode `json:"args"`
	Cases  []InlineNode   `json:"cases"`
}

func MakeAll_CasesRuleNode(
	name string,
	rtype RuleType,
	descr string,
	source string,
	args []NamedArgNode,
	cases []InlineNode,
) CasesRuleNode {
	return CasesRuleNode{
		_CasesRuleNode{
			Name:   name,
			Rtype:  rtype,
			Descr:  descr,
			Source: source,
			Args:   args,
			Cases:  cases,
		},
	}
}

func Make_CasesRuleNode(
	name string,
	rtype RuleType,
	descr string,
	source string,
	args []NamedArgNode,
	cases []InlineNode,
) CasesRuleNode {
	ret := CasesRuleNode{
		_CasesRuleNode{
			Name:   name,
			Rtype:  rtype,
			Descr:  descr,
			Source: source,
			Args:   args,
			Cases:  cases,
		},
	}
	return ret
}

type GrammarNode struct {
	_GrammarNode
}

type _GrammarNode struct {
	Name       string              `json:"name"`
	Rule_names []string            `json:"rule_names"`
	Rules      map[string]RuleNode `json:"rules"`
}

func MakeAll_GrammarNode(
	name string,
	rule_names []string,
	rules map[string]RuleNode,
) GrammarNode {
	return GrammarNode{
		_GrammarNode{
			Name:       name,
			Rule_names: rule_names,
			Rules:      rules,
		},
	}
}

func Make_GrammarNode(
	name string,
	rule_names []string,
	rules map[string]RuleNode,
) GrammarNode {
	ret := GrammarNode{
		_GrammarNode{
			Name:       name,
			Rule_names: rule_names,
			Rules:      rules,
		},
	}
	return ret
}

type GrammarsNode struct {
	_GrammarsNode
}

type _GrammarsNode struct {
	Gmr_names []string               `json:"gmr_names"`
	Grammars  map[string]GrammarNode `json:"grammars"`
}

func MakeAll_GrammarsNode(
	gmr_names []string,
	grammars map[string]GrammarNode,
) GrammarsNode {
	return GrammarsNode{
		_GrammarsNode{
			Gmr_names: gmr_names,
			Grammars:  grammars,
		},
	}
}

func Make_GrammarsNode(
	gmr_names []string,
	grammars map[string]GrammarNode,
) GrammarsNode {
	ret := GrammarsNode{
		_GrammarsNode{
			Gmr_names: gmr_names,
			Grammars:  grammars,
		},
	}
	return ret
}

type InlineNode struct {
	_InlineNode
}

type _InlineNode struct {
	Case_name string         `json:"case_name"`
	Source    string         `json:"source"`
	Args      []NamedArgNode `json:"args"`
}

func MakeAll_InlineNode(
	case_name string,
	source string,
	args []NamedArgNode,
) InlineNode {
	return InlineNode{
		_InlineNode{
			Case_name: case_name,
			Source:    source,
			Args:      args,
		},
	}
}

func Make_InlineNode(
	case_name string,
	source string,
	args []NamedArgNode,
) InlineNode {
	ret := InlineNode{
		_InlineNode{
			Case_name: case_name,
			Source:    source,
			Args:      args,
		},
	}
	return ret
}

type ListNode struct {
	_ListNode
}

type _ListNode struct {
	Elem ArgNode `json:"elem"`
}

func MakeAll_ListNode(
	elem ArgNode,
) ListNode {
	return ListNode{
		_ListNode{
			Elem: elem,
		},
	}
}

func Make_ListNode(
	elem ArgNode,
) ListNode {
	ret := ListNode{
		_ListNode{
			Elem: elem,
		},
	}
	return ret
}

type NObjNode struct {
	_NObjNode
}

type _NObjNode struct {
}

func MakeAll_NObjNode() NObjNode {
	return NObjNode{
		_NObjNode{},
	}
}

func Make_NObjNode() NObjNode {
	ret := NObjNode{
		_NObjNode{},
	}
	return ret
}

type Named[N any] struct {
	_Named[N]
}

type _Named[N any] struct {
	Name string `json:"name"`
	Node N      `json:"node"`
}

func MakeAll_Named[N any](
	name string,
	node N,
) Named[N] {
	return Named[N]{
		_Named[N]{
			Name: name,
			Node: node,
		},
	}
}

func Make_Named[N any](
	name string,
	node N,
) Named[N] {
	ret := Named[N]{
		_Named[N]{
			Name: name,
			Node: node,
		},
	}
	return ret
}

type NamedArgNode Named[ArgNode]

type NontNode struct {
	_NontNode
}

type _NontNode struct {
	Rule string `json:"rule"`
}

func MakeAll_NontNode(
	rule string,
) NontNode {
	return NontNode{
		_NontNode{
			Rule: rule,
		},
	}
}

func Make_NontNode(
	rule string,
) NontNode {
	ret := NontNode{
		_NontNode{
			Rule: rule,
		},
	}
	return ret
}

type OptNode struct {
	_OptNode
}

type _OptNode struct {
	Elem ArgNode `json:"elem"`
}

func MakeAll_OptNode(
	elem ArgNode,
) OptNode {
	return OptNode{
		_OptNode{
			Elem: elem,
		},
	}
}

func Make_OptNode(
	elem ArgNode,
) OptNode {
	ret := OptNode{
		_OptNode{
			Elem: elem,
		},
	}
	return ret
}

type RuleDetailNode struct {
	Branch RuleDetailNodeBranch
}

type RuleDetailNodeBranch interface {
	isRuleDetailNodeBranch()
}

func (*RuleDetailNode) MakeNewBranch(key string) (any, error) {
	switch key {
	case "inline":
		return &_RuleDetailNode_Inline{}, nil
	case "bare":
		return &_RuleDetailNode_Bare{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _RuleDetailNode_Inline struct {
	V InlineNode `branch:"inline"`
}
type _RuleDetailNode_Bare struct {
	V BareNode `branch:"bare"`
}

func (_RuleDetailNode_Inline) isRuleDetailNodeBranch() {}
func (_RuleDetailNode_Bare) isRuleDetailNodeBranch()   {}

func Make_RuleDetailNode_inline(v InlineNode) RuleDetailNode {
	return RuleDetailNode{
		_RuleDetailNode_Inline{v},
	}
}

func Make_RuleDetailNode_bare(v BareNode) RuleDetailNode {
	return RuleDetailNode{
		_RuleDetailNode_Bare{v},
	}
}

func (un RuleDetailNode) Cast_inline() (InlineNode, bool) {
	br, ok := un.Branch.(_RuleDetailNode_Inline)
	return br.V, ok
}

func (un RuleDetailNode) Cast_bare() (BareNode, bool) {
	br, ok := un.Branch.(_RuleDetailNode_Bare)
	return br.V, ok
}

func Handle_RuleDetailNode[T any](
	_in RuleDetailNode,
	inline func(inline InlineNode) T,
	bare func(bare BareNode) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _RuleDetailNode_Inline:
		if inline != nil {
			return inline(_b.V)
		}
	case _RuleDetailNode_Bare:
		if bare != nil {
			return bare(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleDetailNode")
}

func HandleWithErr_RuleDetailNode[T any](
	_in RuleDetailNode,
	inline func(inline InlineNode) (T, error),
	bare func(bare BareNode) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _RuleDetailNode_Inline:
		if inline != nil {
			return inline(_b.V)
		}
	case _RuleDetailNode_Bare:
		if bare != nil {
			return bare(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleDetailNode")
}

type RuleNode struct {
	Branch RuleNodeBranch
}

type RuleNodeBranch interface {
	isRuleNodeBranch()
}

func (*RuleNode) MakeNewBranch(key string) (any, error) {
	switch key {
	case "bare_rule":
		return &_RuleNode_Bare_rule{}, nil
	case "virt_rule":
		return &_RuleNode_Virt_rule{}, nil
	case "case_rule":
		return &_RuleNode_Case_rule{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _RuleNode_Bare_rule struct {
	V BareRuleNode `branch:"bare_rule"`
}
type _RuleNode_Virt_rule struct {
	V VirtRuleNode `branch:"virt_rule"`
}
type _RuleNode_Case_rule struct {
	V CasesRuleNode `branch:"case_rule"`
}

func (_RuleNode_Bare_rule) isRuleNodeBranch() {}
func (_RuleNode_Virt_rule) isRuleNodeBranch() {}
func (_RuleNode_Case_rule) isRuleNodeBranch() {}

func Make_RuleNode_bare_rule(v BareRuleNode) RuleNode {
	return RuleNode{
		_RuleNode_Bare_rule{v},
	}
}

func Make_RuleNode_virt_rule(v VirtRuleNode) RuleNode {
	return RuleNode{
		_RuleNode_Virt_rule{v},
	}
}

func Make_RuleNode_case_rule(v CasesRuleNode) RuleNode {
	return RuleNode{
		_RuleNode_Case_rule{v},
	}
}

func (un RuleNode) Cast_bare_rule() (BareRuleNode, bool) {
	br, ok := un.Branch.(_RuleNode_Bare_rule)
	return br.V, ok
}

func (un RuleNode) Cast_virt_rule() (VirtRuleNode, bool) {
	br, ok := un.Branch.(_RuleNode_Virt_rule)
	return br.V, ok
}

func (un RuleNode) Cast_case_rule() (CasesRuleNode, bool) {
	br, ok := un.Branch.(_RuleNode_Case_rule)
	return br.V, ok
}

func Handle_RuleNode[T any](
	_in RuleNode,
	bare_rule func(bare_rule BareRuleNode) T,
	virt_rule func(virt_rule VirtRuleNode) T,
	case_rule func(case_rule CasesRuleNode) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _RuleNode_Bare_rule:
		if bare_rule != nil {
			return bare_rule(_b.V)
		}
	case _RuleNode_Virt_rule:
		if virt_rule != nil {
			return virt_rule(_b.V)
		}
	case _RuleNode_Case_rule:
		if case_rule != nil {
			return case_rule(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleNode")
}

func HandleWithErr_RuleNode[T any](
	_in RuleNode,
	bare_rule func(bare_rule BareRuleNode) (T, error),
	virt_rule func(virt_rule VirtRuleNode) (T, error),
	case_rule func(case_rule CasesRuleNode) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _RuleNode_Bare_rule:
		if bare_rule != nil {
			return bare_rule(_b.V)
		}
	case _RuleNode_Virt_rule:
		if virt_rule != nil {
			return virt_rule(_b.V)
		}
	case _RuleNode_Case_rule:
		if case_rule != nil {
			return case_rule(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleNode")
}

type RuleType struct {
	Branch RuleTypeBranch
}

type RuleTypeBranch interface {
	isRuleTypeBranch()
}

func (*RuleType) MakeNewBranch(key string) (any, error) {
	switch key {
	case "define":
		return &_RuleType_Define{}, nil
	case "override":
		return &_RuleType_Override{}, nil
	case "extend":
		return &_RuleType_Extend{}, nil
	}
	return nil, fmt.Errorf("unknown branch is : %s", key)
}

type _RuleType_Define struct {
	V struct{} `branch:"define"`
}
type _RuleType_Override struct {
	V struct{} `branch:"override"`
}
type _RuleType_Extend struct {
	V struct{} `branch:"extend"`
}

func (_RuleType_Define) isRuleTypeBranch()   {}
func (_RuleType_Override) isRuleTypeBranch() {}
func (_RuleType_Extend) isRuleTypeBranch()   {}

func Make_RuleType_define() RuleType {
	return RuleType{
		_RuleType_Define{struct{}{}},
	}
}

func Make_RuleType_override() RuleType {
	return RuleType{
		_RuleType_Override{struct{}{}},
	}
}

func Make_RuleType_extend() RuleType {
	return RuleType{
		_RuleType_Extend{struct{}{}},
	}
}

func (un RuleType) Cast_define() (struct{}, bool) {
	br, ok := un.Branch.(_RuleType_Define)
	return br.V, ok
}

func (un RuleType) Cast_override() (struct{}, bool) {
	br, ok := un.Branch.(_RuleType_Override)
	return br.V, ok
}

func (un RuleType) Cast_extend() (struct{}, bool) {
	br, ok := un.Branch.(_RuleType_Extend)
	return br.V, ok
}

func Handle_RuleType[T any](
	_in RuleType,
	define func(define struct{}) T,
	override func(override struct{}) T,
	extend func(extend struct{}) T,
	_default func() T,
) T {
	switch _b := _in.Branch.(type) {
	case _RuleType_Define:
		if define != nil {
			return define(_b.V)
		}
	case _RuleType_Override:
		if override != nil {
			return override(_b.V)
		}
	case _RuleType_Extend:
		if extend != nil {
			return extend(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleType")
}

func HandleWithErr_RuleType[T any](
	_in RuleType,
	define func(define struct{}) (T, error),
	override func(override struct{}) (T, error),
	extend func(extend struct{}) (T, error),
	_default func() (T, error),
) (T, error) {
	switch _b := _in.Branch.(type) {
	case _RuleType_Define:
		if define != nil {
			return define(_b.V)
		}
	case _RuleType_Override:
		if override != nil {
			return override(_b.V)
		}
	case _RuleType_Extend:
		if extend != nil {
			return extend(_b.V)
		}
	}
	if _default != nil {
		return _default()
	}
	panic("unhandled branch in : RuleType")
}

type TermNode struct {
	_TermNode
}

type _TermNode struct {
}

func MakeAll_TermNode() TermNode {
	return TermNode{
		_TermNode{},
	}
}

func Make_TermNode() TermNode {
	ret := TermNode{
		_TermNode{},
	}
	return ret
}

type VirtRuleNode Named[BareRuleNode]
