'use strict';

const fastGlob = require('fast-glob');
const fs = require('fs');
const ohm = require('ohm-js');
const path = require('path');

const {generateTypes} = require('../../helpers/generateTypes');

class Plan {
  constructor() {
    this.plan = {filesToWrite: Object.create(null)};
  }

  write(filename, contents) {
    this.plan.filesToWrite[filename] = contents;
  }
}

class Writer {
  constructor(basePath) {
    this.basePath = basePath || '';
  }

  write(filename, contents) {
    const outputPath = path.join(this.basePath, filename);
    console.log(outputPath); // eslint-disable-line no-console
    fs.writeFileSync(outputPath, contents);
  }
}

const createBanner = (filename = undefined) =>
  `// AUTOGENERATED FILE
// This file was generated${
    filename ? ` from ${filename}` : ''
} by 'generate-ohm-declarations'.`;

function generateRecipes(patterns, opts) {
  const {dryRun, cwd, withTypes} = opts;
  const plan = new Plan();
  const writer = dryRun ? plan : new Writer(cwd);

  for (const sourceFilename of fastGlob.sync(patterns, {cwd})) {
    const sourcePath = cwd ? path.join(cwd, sourceFilename) : sourceFilename;
    const grammarSource = fs.readFileSync(sourcePath, 'utf-8');
    const grammar = ohm.grammar(grammarSource);

    generateRecipe(sourceFilename, grammar, writer);
    if (withTypes) {
      generateTypesWithWriter(sourceFilename, grammar, writer);
    }
  }

  return plan.plan;
}

function generateRecipe(grammarPath, grammar, writer) {
  const outputFilename = `${grammarPath}.js`;
  writer.write(
      outputFilename,
      `module.exports = require('ohm-js').makeRecipe('${grammar.toRecipe()});`
  );
}

function generateTypesWithWriter(grammarPath, grammar, writer) {
  const typeDecls = generateTypes(grammar);
  const filename = path.basename(grammarPath);
  const contents = [createBanner(filename), '', typeDecls].join('\n');
  writer.write(`${grammarPath}.d.ts`, contents);
}

module.exports = {
  command: 'generateRecipes <patterns...>',
  description: 'generate standalone modules (aka "recipes") from .ohm files',
  options: [['-t, --withTypes', 'generate a corresponding .d.ts file for TypeScript']],
  action: generateRecipes
};
