name: Publish Preview Packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm --version
      - run: pnpm install
      - run: pnpm build
      - run: pnpm dlx pkg-pr-new publish './packages/compiler' './packages/runtime' './packages/to-ast-compat'
